### PR TITLE
[MIG] account_chatter: Migration to 14.0 vx#43062

### PR DESCRIPTION
**Pull request by deivislaya**
Migration Standard

### CODE REVIEW

**Comment by luisg123v** [comment]
@deivislaya first migrate to v13, please.

**Comment by deivislaya** [comment]
> @deivislaya first migrate to v13, please.

@luisg123v

Ready!  #1471 

Regards!

**Comment by randall-vx** [comment]
@luisg123v do you have any news about thos PR ?

cc: @deivislaya

**Comment by randall-vx** [comment]
Hi @luisg123v do you have any news about thos PR ?

**Comment by luisg123v** [comment]
@randall-vx lets review/merge first https://github.com/Vauxoo/addons-vauxoo/pull/1471, as this one should containg the full history, including the migration to 13.0

**Comment by deivislaya** [comment]
@luisg123v  @randall-vx 

Ready the full history, including the migration to 13.0

Regards!

**Review by luisg123v — APPROVED** [review]

**Pull request merged**
