### PR TITLE
[FIX] sale_margin_percentage: Migrated to new configuration models

### PR DESCRIPTION
**Pull request by deivislaya**
vx#8888

**TODO**

- [x] Changed name of file
- [x] Adjust configuration view in sales
- [x] Modified method default for margin

### CODE REVIEW

**Comment by JulioSerna** [comment]
is there pr dummy to test this pr?

**Comment by deivislaya** [comment]
Hi @JulioSerna @suniagajose 

This PR is ready for review

**Comment by suniagajose** [comment]
hi @deivislaya 

I recently review your Dummy PR...

The field Margin Threshold in Sale Configuration don't show when Margins feature is enable...

general settings - odoo

Could you check this please?

Thanks,

**Comment by deivislaya** [comment]
Hi @suniagajose 

The Margin Threshold field is displayed when you activate the developer mode because it belongs to the group [Technical](https://github.com/Vauxoo/addons-vauxoo/pull/1229/files#diff-e04ee64d330fd0af3daad1b48292f260R10) from `saas-14` version,  however I do not know if this is still valid

**Review by suniagajose — APPROVED** [review]

**Pull request merged**
