### PR TITLE
[ADD] import_tax_tariff: Add missing translations to module.

### PR DESCRIPTION
**Pull request by KarenKawaii**
## [VX#5101](https://www.vauxoo.com/web#id=5101&view_type=form&model=project.task&action=138)
- [x] Add missing translations to `import_tax_tariff`
- [x] Create [PR#990](https://github.com/Vauxoo/yoytec/pull/990) dummy. 
- [x] Rebase.

### CODE REVIEW

**Comment by moylop260** [comment]
@KarenKawaii 
Could you patch odoo with follow pr https://github.com/Vauxoo/odoo/pull/95 to fix a issue to get all translations source?

**Comment by KarenKawaii** [comment]
[PR#990](https://github.com/Vauxoo/yoytec/pull/990) dummy.

**Comment by KarenKawaii** [comment]
Hello @moylop260 I patched odoo locally to get the missing translations in this module.

**Comment by KarenKawaii** [comment]
The check was green for this PR, also in the related PR dummy the translations are loaded successfully:
translations_import_tax_tariff

**Pull request merged**
