### PR TITLE
[ADD] Add invoice field of type char on picking model.

### PR DESCRIPTION
**Pull request by yaniaular**
[HU # 985](https://www.vauxoo.com/web?db=vauxoo#id=985&view_type=form&model=user.story)
CA # 3

invoice field

### CODE REVIEW

**Comment by yaniaular** [comment]
@gquilarque Please review...

**Comment by moylop260** [comment]
Dummy pr of this one?

**Comment by yaniaular** [comment]
@moylop260 https://github.com/Vauxoo/yoytec/pull/280

**Comment by moylop260** [comment]
https://github.com/Vauxoo/yoytec/pull/280

**Comment by gquilarque** [comment]
Hello @yaniaular, please put the new field after field owner_id.

Thank you.

**Comment by yaniaular** [comment]
@gquilarque It's ready, now waiting by pr dummy in yoytec https://github.com/Vauxoo/yoytec/pull/280

**Comment by yaniaular** [comment]
@gquilarque ready to merge

**Comment by moylop260** [comment]
remove wip

**Pull request merged**
