### PR TITLE
[ADD][base_vat_country]Added module to complete country code in the VAT

### PR DESCRIPTION
**Pull request by luistorresm**

### CODE REVIEW

**Comment by moylop260** [comment]
- Create a dummy pr to other project that used this module
- Fix lints errors

**Comment by luistorresm** [comment]
@JulioSerna 
Puedes darme un +1 por favor?

Saludos

**Comment by moylop260** [comment]
dummy pr?

**Comment by luistorresm** [comment]
Dummy PR

https://github.com/Vauxoo/lodigroup/pull/283

**Pull request merged**
