### PR TITLE
[MIG] account_refund_early_payment: Migrate to  version 12.0

### PR DESCRIPTION
**Pull request by luisg123v**
The following changes were performed:
- Bump version
- Fix references to external IDs
- Re-write tests. They didn't work probably from a long time ago,
  because they relied on workflows
- Remove encoding and long license from headers, use short license only
- Use plural for directories: wizard -> wizards
- Move views for wizards to the wizards directory
- Remove all redundant .po files, as their content was te same, only
  `es.po` was left
- Migrate and update translation terms
- Remove deprecated keys from manifest
- Replace openerp by odoo on import statements and XML tags
- Fix lints
- Fix typos on the README
- Small code clean-up

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 
Could you check why MQT is failing here when installing apt dependencies?

CC @yaniaular

**Comment by keylor2906** [comment]
Hello @luisg123v I also had a first approach of forwardporting this module from v11.0 to 12.0 on this PR https://github.com/Vauxoo/addons-vauxoo/pull/1337

**Comment by keylor2906** [comment]
@yaniaular @moylop260 Could you please review/merge one of the migration PRs of early payment, I understand this module is needed on absa, but is also needed for macom

**Review by luistorresm — CHANGES_REQUESTED** [review]
@keylor2906 

Could you join the commits that are related, please?

Example

c39d324 [IMP] pep8, pylint and pyflakes8
4695c80 [IMP] pep8, pylint and pyflakes8

**Comment by keylor2906** [comment]
@luistorresm  This PR belongs to @luisg123v

**Comment by luistorresm** [comment]
@luisg123v 
 
Could you review my last comment, please?

Regards

**Comment by luisg123v** [comment]
@luistorresm  
Done. However, After reviewing all commits, I was only able to take down the number of commits from 61 to 58. For example, I tried to squash similar commits that fixes lints that were not just next to each oter, but when I tried to move them, conflicts popped up.

**Review by luistorresm — APPROVED** [review]

**Comment by keylor2906** [comment]
@moylop260 @yaniaular Could you please review/merge this?

**Pull request merged**
