### PR TITLE
[ADD] Add stock_location_code module

### PR DESCRIPTION
**Pull request by echeverrifm**
Add stock_location_code Module

### CODE REVIEW

**Comment by nhomar** [comment]
@zaoral Did you test this PR on runbot, can you give me you +1 in order to be sure we comply your expectations as owner of the first coding process.

Regards

**Comment by zaoral** [comment]
@nhomar I try several time last night to run the PR in runbot but the run was killed everytime. I talk to @echeverrifm about that. Is a priority, today I will try to test it again and I will give you feedback.

**Comment by zaoral** [comment]
@nhomar @echeverrifm the functional test was made in the runbot, everything works properly. I made a mini video showing the function http://youtu.be/SY84cHPQ-aI This video can be use as documentation. However, before make the merge there is a problem to resolve, the runbot is red http://odoorunbot.vauxoo.com/runbot/build/29059.

Regards

**Comment by zaoral** [comment]
+1

**Pull request merged**
