### PR TITLE
fix appending record set

### PR DESCRIPTION
**Pull request by yk2kus**
fix : AttributeError: 'product.product' object has no attribute 'append'

### CODE REVIEW

**Comment by nhomar** [comment]
@josemoralesp can you give me a :+1: here please?

**Comment by moylop260** [comment]
@josemoralesp 
Maybe, next sentence require a refactory too
`p_ids = this.product_ids and this.product_ids`

**Comment by nhomar** [comment]
@josemoralesp ping, please check this in order to know if it can be merged.

**Comment by luisg123v** [comment]
This has conflicts and source branch doesn't exist, so it cannot be fixed. Closing

**Pull request closed without merging**
