### PR TITLE
[MIG] account_refund_early_payment: Migration to V13.0

### PR DESCRIPTION
**Pull request by luiseevaquer**

### CODE REVIEW

**Comment by luiseevaquer** [comment]
Hi @hugho-ad 

Could you review this PR please?

**Comment by hugho-ad** [comment]
@lescobarvx 

pls, create a dummy mr where we can test it

**Comment by hugho-ad** [comment]
@lescobarvx 

status?

**Comment by hugho-ad** [comment]
@lescobarvx 
missing status of this

**Pull request closed without merging**
