### PR TITLE
[FIX] supplier_invoice_number_unique: fixed traceback on tests trigge…

### PR DESCRIPTION
**Pull request by keylor2906**
…red by the unique constraint at the invoice validation event task

Dummy wohlert: https://github.com/Vauxoo/wohlert/pull/98

Dummy lodigroup: https://github.com/Vauxoo/lodigroup/pull/763

### CODE REVIEW

**Comment by keylor2906** [comment]
@luistorresm could you review this please

**Comment by luistorresm** [comment]
@keylor2906 

Please add a dummy PR to lodigroup,

**Comment by keylor2906** [comment]
@luistorresm could you review please, this pr already fix the problems of wohlert related to this repo

**Review by luistorresm — APPROVED** [review]
@josemoralesp 

Could you approve this PR, please?

Regards

**Comment by josemoralesp** [comment]
:+1:

**Review by luistorresm — COMMENTED** [review]
@dsabrinarg 

Could you merge this PR, please?

Regards

**Pull request merged**
