### PR TITLE
[IMP]added _parent_store options to product_public_category and field parent left and right  in order to improve queries

### PR DESCRIPTION
**Pull request by hugho-ad**
- [x] IMP, compute total_tree_products and has_products_ok fields in same compute function

### CODE REVIEW

**Comment by hugho-ad** [comment]
@moylop260 can you review please.

I tried something like [1], but I choose use `child_of` operator since that operator takes the semantics of the model (parent_ id, left, right)
image

[1]

``` python
request = """
                select count(c.id)
                    From product_public_category as c
                    where c.parent_left > %s AND c.parent_right < %s ;"""
            self._cr.execute(
                request, (record.parent_left, record.parent_right))
```

**Comment by moylop260** [comment]
@hugho-ad 
You are right!
LGTM!

Could you review follow detail:
`2016-02-04 20:07:06,810 255 INFO openerp_test openerp.modules.module: module website_product_filters: creating or updating database tables
2016-02-04 20:07:06,995 255 ERROR openerp_test openerp.models: The column parent_id on object product.public.category must be set as ondelete='cascade' or 'restrict'` in the runbot of dummy pr.

**Comment by hugho-ad** [comment]
@moylop260 Rubot green
https://github.com/Vauxoo/yoytec/pull/685

**Comment by hugho-ad** [comment]
@josemoralesp 

Using a write function like next:

``` python
@api.depends("product_ids", "product_ids.website_published")
    def _get_product_count(self):
        prod_obj = self.env["product.template"]
        for rec in self:
            prod_ids = prod_obj.search(
                [('public_categ_ids', 'child_of', rec.id),
                 ('website_published', '=', True)])
            total_tree_products = len(prod_ids)
            has_products_ok =  len(prod_ids) > 0
            rec.write({
                'total_tree_products': total_tree_products,
                'has_products_ok': has_products_ok
                })
```

Triggers me next error:

``` python
File "/.repo_requirements/odoo/openerp/tools/func.py", line 68, in wrapper
    lock.release()
  File "/usr/lib/python2.7/threading.py", line 212, in release
    self._note("%s.release(): non-final release", self)
RuntimeError: maximum recursion depth exceeded

```

Try it your self.

Regards

**Pull request merged**
