### PR TITLE
[DEL] migrated to cliente app

### PR DESCRIPTION
**Pull request by hugho-ad**
- website_order_confirm
  Deleted, this module only overwrite the function payment_validate in
  order to enable direct creation of Sale Order directly from website
  instead of creating a Quotation.

### CODE REVIEW

**Comment by nhomar** [comment]
- Nobody depends of it?
- Can you extend a little here what this was doing in order to have it as comment please.

**Comment by hugho-ad** [comment]
Talking with @oscarolar , this module is Not necessary to Delete.

**Comment by nhomar** [comment]
Can you enlight me Why? what were the conclusions of that meeting please?

**Comment by hugho-ad** [comment]
The module works, and is not necessary  remove them, just delete the dependency

**Pull request closed without merging**
