### PR TITLE
[IMP] split a item and no repeat the lot

### PR DESCRIPTION
**Pull request by yaniaular**
[HU # 985](https://www.vauxoo.com/web?db=vauxoo#id=985&view_type=form&model=user.story)
CA # 2

split
plit a item and no repeat the lot

### CODE REVIEW

**Comment by yaniaular** [comment]
@gquilarque please review

**Comment by yaniaular** [comment]
PR dummy https://github.com/Vauxoo/yoytec/pull/283

**Comment by yaniaular** [comment]
@nhomar merge please..

**Comment by gquilarque** [comment]
:+1:

**Pull request merged**
