### PR TITLE
[REF] Hide input ruc when company is foreign and better look for controller erros tags HU#614, CA#12,14,15

### PR DESCRIPTION
**Pull request by hugho-ad**
[HU#614](https://www.vauxoo.com/web#id=614&view_type=form&model=user.story&action=726)

Before
image

After
image

Etiquetas 'required'
Antes:
image

Despues:
image

### CODE REVIEW

**Comment by hugho-ad** [comment]
@oscarolar me apoyas con un +1 porfavor.

**Comment by hugho-ad** [comment]
@oscarolar me apoyas con un +1

**Comment by oscarolar** [comment]
Everything seems ok, but please add some screenshots before and after, this can help me to review the UI changes, thanks.

**Comment by hugho-ad** [comment]
@oscarolar screenshots added

**Comment by oscarolar** [comment]
:+1:  @nhomar can  you merge this please?

**Pull request merged**
