### PR TITLE
[ADD] add new module purchase_changeless_move_lines to restrict the addition or modification of the move lines related to a picking generate from a purchase order

### PR DESCRIPTION
**Pull request by zaoral**
Task [vx#3619](https://www.vauxoo.com/#id=3619&view_type=form&model=project.task) HU [346](https://www.vauxoo.com/?debug=#id=346&view_type=form&model=user.story&action=726) Sprint 13

### CODE REVIEW

**Comment by zaoral** [comment]
- travis show pylint and flake8 errors but external to the current developed module.
- runbot show error at module openerp.addons.account.tests.test_reconciliation.

@nhomar this PR is ready to review

**Comment by zaoral** [comment]
@nhomar part of this PR contain a purchase_id compute field added to the stock.picking model to indentify when a stock picking is related to a purchase order. Searching about this if it is a good approach I found this PR in the community odoo/odoo#3376. Please way for you feedback.

**Comment by nhomar** [comment]
Hello Kath.
- The feature is incomplete.

Please add the following test cases.

_case 1_
1. Create a PO (Invoice from Picking policy).
2. Validate Picking.
3. Validate Invoice.

_case 2_
1. Create a PO (Invoice Order).
2. Validate Picking.
3. Validate Invoice.
- Add the Following Feature:

a. The blocking point must be optional, it means, the Purchase Manager must be able to have a clear and easy to use workaround to manage Purchase Order Exceptions in order to be sure and manage concepts like "Fill Rates" which is the fact of measure differences between what was asked for and what was explicitally delivered.
b. On the methods which validate the picking, then we need to add a contraint/warning informing the user they can not validate anything different from the purchase Order.

**Comment by zaoral** [comment]
@nhomar ok. I start working on the changes.

**Comment by nhomar** [comment]
@zaoral THis PR have PEP8 errors can you tell me if we can merge it please.

Regards.

**Comment by zaoral** [comment]
@nhomar please review this PR
Is related to HU#346 Task vx#3619
It was left behind.

Please review and if you approve it then I will proceed wit the rebase before merge

Best Regards.

**Pull request merged**
