### PR TITLE
[MERGE] test and apply pylint/flake fixes to message_post_model and message_post_test modules.

### PR DESCRIPTION
**Pull request by zaoral**
This PR correspond to Task [vx#2541](https://www.vauxoo.com/#id=2541&view_type=form&model=project.task) HU [770](https://www.vauxoo.com/#id=770&view_type=form&model=user.story)

NOTE: This migration is a just basic one with the minimal changes to ensure that the modules developed in openerp v7  works propertly in odoo v8. Also, just for standard flake8 and pylint were applied to the code to ensure that our testing tool going to work when testing this module as a dependency of our clients instances.

In a future,  a more deep level migration can be done for this modue by changing the current code from api v7 to the new api v8.

### CODE REVIEW

**Comment by zaoral** [comment]
@moylop260 please do this merge.

**Comment by moylop260** [comment]
@zaoral 
Puedes generar un runbot con donde se instale este módulo.
Tal vez tengas que generar una PR con el depends al proyecto que se instalará, y generar un prebuild con esta configuración.

**Comment by moylop260** [comment]
@zaoral 
Que ha pasado al respecto?

**Comment by yaniaular** [comment]
Migration message_post_model module form 7.0 to 8.0 To use message post in claim.

<a href="https://www.vauxoo.com/#id=770&view_type=form&model=user.story">HU 770</a>
<a href="https://www.vauxoo.com/#id=2541&view_type=form&model=project.task&menu_id=136&action=138">Task 2541</a>

**Comment by zaoral** [comment]
@yaniaular This PR was forgotten, I will proceed to resolve the merge conflicts and generate the runbot like it was asked by @moylop260

**Comment by yaniaular** [comment]
@zaoral Thanks you :+1:

**Comment by zaoral** [comment]
Waiting for runbot http://runbot.vauxoo.com/runbot/team/yoytec-12#8_0-yoytec%20%5BVauxoo_addons-vauxoo_70%5D

Note: addons-vauxoo module only is check using runbot. There is no travis/shippable test

**Comment by zaoral** [comment]
The runbot is green http://runbot.vauxoo.com/runbot/team/yoytec-12#8_0-yoytec%20%5BVauxoo_addons-vauxoo_70%5D

@yaniaular please review and merge.

**Comment by yaniaular** [comment]
@zaoral the message_post_model module works in odoo 8.0? but not that API 8.0.  this is correct?

**Comment by zaoral** [comment]
@yaniaular indeed

This migration is a just basic one with the minimal changes to ensure that the modules developed in openerp v7 works propertly in odoo v8. Also, just for standard flake8 and pylint were applied to the code to ensure that our testing tool going to work when testing this module as a dependency of our clients instances.

In a future, a more deep level migration can be done for this modue by changing the current code from api v7 to the new api v8.

**Pull request merged**
