### PR TITLE
[FIX] default_warehouse_from_sale_team: Fix case of searching a stock…

### PR DESCRIPTION
**Pull request by keylor2906**
… rule when there is no warehouse parameter, like when is done by stock rules when the move destination location is for a different company https://github.com/Vauxoo/odoo/blob/8af8846c88bd04bcf3fa0bcbe4a720b415f994a4/addons/stock/models/stock_move.py#L830

### CODE REVIEW

**Comment by suniagajose** [comment]
@keylor2906 

technically +1

but, we must waiting for a fucntional review.

i let you know right here when functional review is ready!

thanks

**Review by suniagajose — APPROVED** [review]
@keylor2906 

technically +1

but, we must waiting for a fucntional review.

i let you know right here when functional review is ready!

thanks

cc @hugho-ad 
cc @luisg123v 
cc @desdelinux

**Comment by suniagajose** [comment]
Thanks @keylor2906 

Also, can you help us to fw  this up to 16.0 and 17.0.???

Regards,

cc @desdelinux 
cc @hugho-ad 
cc @luisg123v

**Comment by hugho-ad** [comment]
fwp 16.0 https://github.com/Vauxoo/addons-vauxoo/pull/1646

**Pull request merged**
