### PR TITLE
[MERGE] edit travis file to run the new script test_module defined to check our module standard rules. Some rst files where fixed in the process and some pylint/flake8 fixes where made to thouse edited modules.

### PR DESCRIPTION
**Pull request by zaoral**
Task [vx#3892](https://www.vauxoo.com/web#id=3892&view_type=form&model=project.task&action=138)

### CODE REVIEW

**Comment by zaoral** [comment]
I edit one module and fix the related flake8/pylint to force run the new script to check modules

**Comment by zaoral** [comment]
is required to also add:
-  check if the module have doc, and the doc folder have index.html.
- check if all the modules have an icon.png

**Comment by nhomar** [comment]
@zaoral index.rst read the docs for apps.

https://www.odoo.com/apps/upload/

**Comment by zaoral** [comment]
Waiting for testing tools results.

**Comment by zaoral** [comment]
@moylop260 please can yoy help me to fix this errors:

```
************* Module account_voucher_tax.tests.test_bank_statement_customer
account_voucher_tax.tests.test_bank_statement_customer:13: [C0103(invalid-name), TestPaymentTaxCustomer.setUp] Invalid method name "setUp"
************* Module account_voucher_tax.tests.test_bank_statement_cash_flow_supplier
account_voucher_tax.tests.test_bank_statement_cash_flow_supplier:7: [C0103(invalid-name), TestCashFlowTaxSupplier.setUp] Invalid method name "setUp"
************* Module account_voucher_tax.tests.test_bank_statement_cash_flow
account_voucher_tax.tests.test_bank_statement_cash_flow:7: [C0103(invalid-name), TestCashFlowTaxCustomer.setUp] Invalid method name "setUp"
************* Module account_voucher_tax.tests.test_bank_statement
account_voucher_tax.tests.test_bank_statement:13: [C0103(invalid-name), TestPaymentTax.setUp] Invalid method name "setUp"
```

 https://travis-ci.org/Vauxoo/addons-vauxoo/builds/73150059

Are the last fix we need to have this PR with travis green.

Best regards.

**Comment by moylop260** [comment]
@zaoral 
This matter is more hadr I will to create a new issue for work this.

**Comment by zaoral** [comment]
ok @moylop260 . I will test again the script with the modifications made to ensure that everything is perfect and let you know when the merge an be done.

**Comment by zaoral** [comment]
@nhomar This PR is ready to review. I made a squash to reduce the commits.into the minimum and remove the history of the check_modules.py.

NOTE: I create a copy of the original branch just in case at here [8.0-vx#3892-kty-cpy](https://github.com/Vauxoo-dev/addons-vauxoo/tree/8.0-vx%233892-kty-cpy)

Best regards

**Comment by moylop260** [comment]
:+1:

**Pull request merged**
