### PR TITLE
[DEL] Removing deprecated modules from addons-vauxoo

### PR DESCRIPTION
**Pull request by JVegaB**
Removed all the 8.0 openerp modules

### CODE REVIEW

**Comment by JVegaB** [comment]
@josemoralesp

**Review by luisg123v — CHANGES_REQUESTED** [review]
I like the idea behind this. Could you solve conflicts, please?

**Comment by luisg123v** [comment]
Since no answer was given and this would need to be re-done due to a lot of conflicts, I'm closing this PR.

**Comment by hugho-ad** [comment]
@JVegaB please, take this againg!

**Comment by luisg123v** [comment]
Superseded by https://github.com/Vauxoo/addons-vauxoo/pull/1446

**Pull request closed without merging**
