### PR TITLE
[ADD] this module adds the field product_model to the product.product object.

### PR DESCRIPTION
**Pull request by oscarolar**

### CODE REVIEW

**Comment by nhomar** [comment]
@oscarolar please can you refer your PR/commits to the user story/task/information related to the "Why" of the module?

**Comment by oscarolar** [comment]
Nhomar here is the [HU](https://www.vauxoo.com/?ts=1426631879796#id=531&view_type=form&model=user.story&menu_id=557&action=726), please review and merge.

**Comment by nhomar** [comment]
Hello @oscarolar 

I do not have Acceptability criterias in the HU.
The commit is doing something else.

Can you please clean up this PR in order to make the merge.

Regards.

**Comment by oscarolar** [comment]
Cleaned.

**Pull request merged**
