### PR TITLE
[FIX] website_product_filters: fix the prices ranges displaying

### PR DESCRIPTION
**Pull request by gomezvillegasdaniel**
This PR https://github.com/Vauxoo/yoytec/pull/1044 points to this PR.
Screenshots on https://github.com/Vauxoo/yoytec/pull/1044

### CODE REVIEW

**Comment by gomezvillegasdaniel** [comment]
@oscarolar

**Comment by hugho-ad** [comment]
@gomezvillegasdaniel Adds some screenshots of before and after please

**Comment by oscarolar** [comment]
@gomezvillegasdaniel please add the yoytec build to the description, in this case you must create a pr to yoytec that  points to this pr in order to get the build green, if you dont this will fail.

**Comment by gomezvillegasdaniel** [comment]
@hugho-ad @oscarolar  screenshots are here https://github.com/Vauxoo/yoytec/pull/1044

**Comment by gomezvillegasdaniel** [comment]
@oscarolar it's green
captura de pantalla 2016-04-15 a las 11 07 20 a m

**Comment by gomezvillegasdaniel** [comment]
@oscarolar https://github.com/Vauxoo/yoytec/pull/1044 It's greeen

**Comment by hugho-ad** [comment]
Functional test :+1: 
@moylop260 @oscarolar  can you merge this please

**Pull request merged**
