### PR TITLE
[IMP] stock_card: adapt stock card to handle transit location different to purchase

### PR DESCRIPTION
**Pull request by JulioSerna**

### CODE REVIEW

**Comment by JulioSerna** [comment]
@hbto 

Could you check/merge this pr?

**Comment by hbto** [comment]
@JulioSerna 
Did you issue a PR with this branch to any of the customer instances?

**Comment by hbto** [comment]
+1

**Comment by hbto** [comment]
Merge when greenlighted on Customer instance

**Comment by JulioSerna** [comment]
@hbto 

[PR DUMMY](https://github.com/Vauxoo/lodigroup/pull/604)
[Runbot PR dummy](http://runbot.vauxoo.com/runbot/build/17208)

**Pull request merged**
