### PR TITLE
[ADD] portal_multicurrency_totals: Show multicurrency totals on portal i#16797

### PR DESCRIPTION
**Pull request by luisg123v**
This module adds te feature to display total amounts by currency when
accessing documents through the portal:
- Quotations
- Sale orders
- Invoices

### Totals in sale orders:

totals_in_so

### Totals in invoices:

totals_in_invoices

Dummy MR: https://git.vauxoo.com/vauxoo/typ/-/merge_requests/905

### CODE REVIEW

**Comment by luisg123v** [comment]
Hi @desdelinux, @imanie383 & @hugho-ad,

Could you review, please?

Regards,

**Comment by imanie383** [comment]
You can create better styles for the totals( tables )
image

and especially invoice totals:
image

**Comment by moylop260** [comment]
Are not there modules in the OCA with this feature?

**Comment by luisg123v** [comment]
@imanie383,

- Regarding the invoice view, I agree with your comments
- Regarding the sale orders view, making it to not be displayed as a table was intentional, because it's like a summary with only two columns and there's no risk of confusion. I'll check with @desdelinux what way we should take here

@moylop260,

I think no, I couldn't find any module that satisfied this requirement, maybe because it's kind of specific.

**Comment by moylop260** [comment]
👍

**Comment by luisg123v** [comment]
@imanie383,

Done, now both cases are displayed as tables, and both uses the same style as Odoo does. This was accorded with @desdelinux 

@desdelinux,

As we discussed by chat, I'm now explicitly excluding draft and cancelled documents. When documents are validated and then cancelled, they still appear in the portal, because the customer is still a follower.

I also added a note in the README pointing that out.

Could you bot review again, please?

Regards,

**Comment by desdelinux** [comment]
LGTM @luisg123v 

@imanie383 With the new style, I think it's enough

**Comment by imanie383** [comment]
@luisg123v 

image

You are duplicating the pager

**Comment by luisg123v** [comment]
@imanie383 you're right! I forgot to remove it.

Done, fixed.

CC @CarmenMiranda

**Comment by imanie383** [comment]
LGTM 👌

**Comment by imanie383** [comment]
@luisg123v 

LGTM 👍

**Pull request merged**
