### PR TITLE
[REF] default_warehouse_from_sale_team: Move fields default_warehouse…

### LINKED ISSUE #1065: [default_warehouse_from_sale_team] Move in view all new fields created in this module.
All fields that are added to Sales Teams model (crm.case.section) should be moved to a single tab in form view.

### PR DESCRIPTION
**Pull request by ysantiago**
Fix #1065 
Close [Vauxoo/typ#46](https://github.com/Vauxoo/typ/pull/46)

### CODE REVIEW

**Comment by ysantiago** [comment]
Hello @JulioSerna can you review this change please.

**Comment by JulioSerna** [comment]
LGTM
sales teams odoo

**Comment by ysantiago** [comment]
@nhomar can you help us with this merge?

**Comment by moylop260** [comment]
In order to avoid a future red travis result, Could you include fix lint?

``` bash
/home/travis/build/Vauxoo/addons-vauxoo/default_warehouse_from_sale_team/__openerp__.py:15:9: E265 block comment should start with '# '
/home/travis/build/Vauxoo/addons-vauxoo/default_warehouse_from_sale_team/__openerp__.py:16:9: E265 block comment should start with '# '
/home/travis/build/Vauxoo/addons-vauxoo/default_warehouse_from_sale_team/models/sales_team.py:6:1: E302 expected 2 blank lines, found 1
************* Module default_warehouse_from_sale_team.models.sales_team
default_warehouse_from_sale_team/models/sales_team.py:97: [W0621(redefined-outer-name), WarehouseDefault.read] Redefining name 'fields' from outer scope (line 3)
default_warehouse_from_sale_team/models/sales_team.py:110: [W0621(redefined-outer-name), WarehouseDefault.read] Redefining name 'fields' from outer scope (line 3)
default_warehouse_from_sale_team/models/sales_team.py:110: [E0102(function-redefined), WarehouseDefault.read] method already defined line 97
************* Module default_warehouse_from_sale_team
default_warehouse_from_sale_team/README.rst:6: [E7901(rst-syntax-error), ]  Enumerated list start value not ordinal-1: "3" (ordinal 3)
```

**Pull request merged**
