### PR TITLE
[FIX] website_product_filters: removed spaces generated by unecessary class

### PR DESCRIPTION
**Pull request by oscarolar**

### CODE REVIEW

**Comment by nhomar** [comment]
@oscarolar AFAICK, this class is necesary for the mobile behavior, didd you check it?

**Comment by oscarolar** [comment]
I dont think so, mt16 = margin-top: 16px;

**Comment by nhomar** [comment]
ok forget it!

**Comment by oscarolar** [comment]
@nhomar Dude, runbot is not working now

**Pull request merged**
