### PR TITLE
[ADD] internal_transfer_with_agreed_amount: New module

### PR DESCRIPTION
**Pull request by edy1192**
1. When foreign currencies are bought, in some cases an amount is agreed for the transaction and it is not exactly that resulting from the official exchange rate.

2. When payments are made or received in foreign currency and the customer or payment service uses its own exchange rate.

For these cases this module allows an internal transfer between different currencies, setting an agreed amount.

This agreed amount will be used to set the amount currency in the journal entries.

A new module is created to avoid duplication of code in different clients that require this process.

### CODE REVIEW

**Comment by edy1192** [comment]
Hi @hbto @luistorresm @moylop260 Could you check this please?

Regards. 😄

**Comment by luistorresm** [comment]
@edy1192 

Could you complete the PR description?

@moylop260 

What do you think about move this module in an OCA repo?

@hbto 

What do you think about the module name?

Regards

**Comment by Ernestomtl** [comment]
Thanks @edy1192 

Could you create a dummy PR for Vauxoo Instance, please?

Regards

**Comment by luistorresm** [comment]
Thanks @edy1192  
 
Could you create a dummy PR for Vauxoo Instance, please? 
 
Regards

**Comment by moylop260** [comment]
There is not ticket/task related
There is not MR dummy related

I can't check it as it

@nhomar 👀

**Comment by edy1192** [comment]
Hi @moylop260 

Sorry for the late reply.

In fact, this came out from Gabriela's request for a payment process with bank commissions, I created the task and here is the meeting [video](https://youtu.be/vhkeAJiq0-4) 

@hbto  can give more information about this.

[Task](https://www.vauxoo.com/web?debug#id=37663&action=470&model=project.task&view_type=form&menu_id=317)

[DUMMY](https://git.vauxoo.com/vauxoo/instance/merge_requests/980)

[test instance](http://t37663-vauxoo120.t01.deployv.com/)

Regards.

cc @luistorresm

**Comment by hbto** [comment]
As commented by @edy1192  at https://github.com/Vauxoo/addons-vauxoo/pull/1393#issuecomment-582111179

This is a requirement needed inside vauxoo, This will allow recording the Transference with the appropriate amount in Local and Foreign currrencies.

I functionally approve this PR.

Regards.

**Comment by hbto** [comment]
:+1:

**Comment by luistorresm** [comment]
@edy1192 

Could you show this feature to @gabyzelg in the Vauxoo instance?

This already is in the customer instance, then I agree with merge this if @gabyzelg approve the feature.

Regards

**Comment by edy1192** [comment]
Hi @luistorresm 

Yes, I'm managing a meeting with @gabyzelg  to show her the feature.

cc @moylop260 @hbto 

Regards

**Comment by edy1192** [comment]
Hi @luistorresm @hbto @moylop260 

Gaby and I met, she agrees with the feature. In fact, she waits for this.

Regards.

**Comment by gabyzelg** [comment]
@edy1192 aprobada la función..

**Pull request merged**
