### PR TITLE
[REF] website_rate_product: Use query with multiple ids

### PR DESCRIPTION
**Pull request by moylop260**
- Refactory to use a query with N ids instead of N queries with one id.
  - Continuation from https://github.com/Vauxoo/yoytec/issues/808#issuecomment-193885012

### CODE REVIEW

**Comment by moylop260** [comment]
I don't ran the cProfile tests and don't ran the pgbadger tests to check values of performance.
I can run if is required.

But by now I have created the PR to review.

FYI @josemoralesp @hugho-ad @oscarolar @nhomar

**Comment by hugho-ad** [comment]
:+1: LGTM

**Comment by oscarolar** [comment]
Just to know, what is going to happen when you add this field on a list view?

**Comment by moylop260** [comment]
> Just to know, What is going to happen when you add this field on a list view?

After change:
work fine!

Before change:
work fine!

Both methods work fine!
It is just a small REF to use a query with N ids instead of N queries with one id.
Continuation from https://github.com/Vauxoo/yoytec/issues/808#issuecomment-193885012

**Comment by oscarolar** [comment]
Good then.

**Comment by moylop260** [comment]
Dummy PR: https://github.com/Vauxoo/yoytec/pull/907

**Comment by josemoralesp** [comment]
IMHO 
The best way to do this it's using one query with multiple ids, because using the other way(one query by id) We will send several queries in a loop to the database and this is not a good practice if we talk about performance

**Pull request merged**
