### PR TITLE
[MIG] stock_by_warehouse_mrp_bom: Module migration from 12.0 to 15.0. T#52780

### PR DESCRIPTION
**Pull request by agarzaarvizu**
### This PR refers to the task [#52,780](https://www.vauxoo.com/web#id=52780&action=1928&model=project.task&view_type=form&cids=1&menu_id=1490)
- Migration of the module stock_by_warehouse_mrp_bom from odoo 12.0 to odoo 15.0

### CODE REVIEW

**Comment by hugho-ad** [comment]
@CarmenMiranda @luisg123v 
could you review pls

**Comment by luisg123v** [comment]
@agarzaarvizu please include commits history. [Here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch) how to do so.

**Comment by CarmenMiranda** [comment]
I agree with @luisg123v in the commits history, and maybe would be a great idea of having 2 different commits in the migration, one per migration (`stock_by_warehouse` and `stock_by_warehouse_mrp_bom`)

**Comment by luisg123v** [comment]
Great @CarmenMiranda, I just told @agarzaarvizu by chat to create two different PRs, one for each module

**Pull request closed without merging**
