### PR TITLE
[REF] product_extended_segmentation: Modified cron job to be split in… task#29961

### PR DESCRIPTION
**Pull request by keylor2906**
… multiple crons, this is done because when having a lot of records is common to have time out errors.

The cron is splited depending the number of records wanted per cron. All crons are linked to the next one to be executed. And when all crons are executed they are deactivated and waiting to be erased by the next execution of the original cron.

### CODE REVIEW

**Comment by keylor2906** [comment]
@dsabrinarg  @josemoralesp  This is the PR to split the cron that computes the product segmentation costs

**Comment by keylor2906** [comment]
This is the dev instance http://dev.lodigroup.com:30013

**Comment by sabrinagnu** [comment]
@JulioSerna @hbto or @josemoralesp review asap please, this is urgente for Quebec customer. Regards!.

**Comment by hbto** [comment]
@dsabrinarg I have reviewed and it's good for me

**Pull request merged**
