### PR TITLE
[FIX] default_warehouse_from_sale_team: update default journal retrieval I#23845

### PR DESCRIPTION
**Pull request by CLaurelB**
Change the method previously used as a default value for the journal_id
to retrieve the default journal to the new method defined to search the
default journal.

### CODE REVIEW

**Comment by CLaurelB** [comment]
@luisg123v could you review, please?

**Review by luisg123v — CHANGES_REQUESTED** [review]
Commit message:
- Title: IMP -> FIX, as this is actually fixing a wrong behavior
- Missing commit description

**Comment by luisg123v** [comment]
FYI @CLaurelB, regarding ticket ID,  T is for tasks, for tickets you should use I. I've fixed it by you.

**Comment by CLaurelB** [comment]
> Commit message:
> 
> * Title: IMP -> FIX, as this is actually fixing a wrong behavior
> * Missing commit description

Title and description updated.

**Comment by CLaurelB** [comment]
@luisg123v could you review again, please?

**Comment by desdelinux** [comment]
ping @luisg123v

**Review by luisg123v — APPROVED** [review]
LGTM :+1:

**Pull request merged**
