### PR TITLE
[FIX]-product_do_merge: Don't consider weight when comparing stock moves

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nhomar** [comment]
Hello,

Thanks for contribuye, can you extender The use case where this pr solve? I do not understand exactly why replace the logic instead correct it.

Thanks again

**Comment by nhomar** [comment]
@josemoralesp can you give your green light here?

**Comment by josemoralesp** [comment]
Hello @lg-clearcorp 

Can you please tell me what are you trying to do here?

I don't understand the reason for your change.

Best Regards.

**Comment by luisg123v** [comment]
Contributor doesn't exist anymore, so closing.

**Pull request closed without merging**
