### PR TITLE
[REF] addons-vauxoo: Add missing , in key license.

### PR DESCRIPTION
**Pull request by KarenKawaii**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@KarenKawaii un this module it's presents the same error 
https://github.com/Vauxoo/addons-vauxoo/blob/8.0/product_category_attributes/__openerp__.py

**Comment by KarenKawaii** [comment]
@hugho-ad I've just fix it. Please, tell me is if another error.

**Comment by hugho-ad** [comment]
:+1:

**Comment by hugho-ad** [comment]
@nhomar can you help us with a review merge please

**Pull request merged**
