### PR TITLE
[REF] aging_due_report: Reduce mccabe rate

### PR DESCRIPTION
**Pull request by moylop260**
- [x] Run tests of the module
- [x] Run with real data

### CODE REVIEW

**Comment by feketemihai** [comment]
@moylop260 I worked lately on the aging_due_report to suit with the improved version of controller_report_xls, please see #860  and i will add your modification in PR, if it's ok for you...

**Comment by moylop260** [comment]
@feketemihai 
Oh I'm late in this party...
Sorry, I added a new pylint check to review the [mccabe rate](https://github.com/PyCQA/pylint) I will rebuild your PR to review this value...
Thanks for contribution

**Comment by nhomar** [comment]
@feketemihai we want merge this with a proper unique PR because the maccabe complexity new checks.

You can left this method untouched and rebase properly once moylop finish it, is it ok for you?

And/or if you simple do not touch this method you will not have any problem I think.

**Comment by moylop260** [comment]
@nhomar 
The PR of @feketemihai touch this method.
He migrated to new api... good job!

**Comment by nhomar** [comment]
Oh! EXCELLENT!

**Comment by feketemihai** [comment]
@nhomar @moylop260 It's up to you...but i think we can leave @moylop260 PR as well and i will do the modification after with the ifs from his PR...in this even if the pr is merged after it will contain the new mccabe rate..

**Comment by moylop260** [comment]
@feketemihai 
Let me see the mccabe rate in your change... a second please...

**Comment by feketemihai** [comment]
@moylop260 IFS are still there, so i don't think it will change a lot...

**Comment by moylop260** [comment]
screen shot 2016-05-11 at 3 31 02 am

**Comment by moylop260** [comment]
This PR reduce the mccabe rate to 7
screen shot 2016-05-11 at 3 35 44 am

**Comment by feketemihai** [comment]
@moylop260 @nhomar I will add these modification to my PR #860.

**Comment by nhomar** [comment]
Ok. Roger that.! we will be adding unittest BTW.

**Comment by feketemihai** [comment]
@nhomar Thanks, you're just making my life harder...spending too much time on this... :smile:

**Comment by moylop260** [comment]
@feketemihai 
hahaha

**Comment by hbto** [comment]
@feketemihai 
No harm meant XD

**Comment by nhomar** [comment]
@feketemihai It is not intentionally xD.

**Comment by feketemihai** [comment]
@moylop260 @nhomar @hbto I was joking...i will add them if needed...

**Comment by hbto** [comment]
@moylop260 

aging_due_report/wizard/wizard.py", line 96, in _get_amount_span
    len_span = len(spans[0]) if spans else 0
TypeError: object of type 'int' has no len()

This error is shown on real data,

regards

**Comment by hbto** [comment]
@feketemihai 
We are joking too,

actually my colleagues @moylop260 & @nhomar  were joking early at me 
because this module is the one with the highest McCabe rating in addons-vauxoo
but one of the most functional ones

Something quite paradoxical XD

**Comment by moylop260** [comment]
I used the following parameters:
5aa96ebd-7e69-4e9b-8c24-4d0926098d5e

With changes and without changes the diff was:
screen shot 2016-05-11 at 5 25 39 am

**Comment by hbto** [comment]
+1 @moylop260 

proceed to squash and merge @nhomar

**Comment by hbto** [comment]
@feketemihai 

Good Day 

You can proceed to rebase https://github.com/Vauxoo/addons-vauxoo/pull/860

from addons-vauxoo 8.0 latest SHA

Best Regards

**Pull request merged**
