### PR TITLE
[ADD] account_invoice_date_due: Date Due now could be updated

### PR DESCRIPTION
**Pull request by luistorresm**
Allow update the date due in an invoice (Even if it's done). To avoid
cancel the invoice and generate again

### CODE REVIEW

**Comment by luistorresm** [comment]
@moylop260 @hbto 

Could you approve/merge this PR, please?

Regards

**Comment by luistorresm** [comment]
@moylop260 

Message from @hbto 

Screen Shot 2019-11-13 at 18 14 55

**Comment by moylop260** [comment]
Could you create a new PR to https://github.com/OCA/account-invoicing and using patches.txt from our project where it is required?

**Comment by luisg123v** [comment]
This is already merged on https://github.com/OCA/account-invoicing/pull/632, so it's no longer required here.

**Pull request closed without merging**
