### PR TITLE
[REF] partner_credit_limit: Inherit send workflow transition  to validate the credit before validate the sales orders.

### PR DESCRIPTION
**Pull request by hugho-ad**
FIX https://github.com/Vauxoo/addons-vauxoo/issues/1081 issue

LODI DUMMY https://github.com/Vauxoo/lodigroup/pull/612 ( CLOSE after merge)

YOYTEC DUMMY https://github.com/Vauxoo/yoytec/pull/2079 (Close After merge)

### CODE REVIEW

**Comment by hugho-ad** [comment]
@dsabrinarg can you help me to review please
This pr solves the issue https://github.com/Vauxoo/addons-vauxoo/issues/1081

Regards!

**Comment by hugho-ad** [comment]
@dsabrinarg can you help me to review please
This pr solves the issue #1081

Regards!

**Comment by hugho-ad** [comment]
@dsabrinarg can you help me to review please
This pr solves the issue #1081

Regards!

**Comment by zaoral** [comment]
Hi @hugho-ad 

Please just as a a preventive action, Could you create a dummy PR to yoytec with the change made here in order to ensure that our client's workflow will still work after we merge this change?

Best Regards

**Comment by hugho-ad** [comment]
@zaoral 
Sure, here is the dummy pr for yoytec
https://github.com/Vauxoo/yoytec/pull/2079

**Comment by zaoral** [comment]
Thanks @hugho-ad

**Comment by hugho-ad** [comment]
@dsabrinarg can you review this pr please, this is necesarry to fix the issue https://github.com/Vauxoo/addons-vauxoo/issues/1081

Regards

**Comment by sabrinagnu** [comment]
Sure, I will today @hugho-ad sorry for the delay here!

**Comment by luisg123v** [comment]
This is abandoned and can't be merged, so closing.

**Pull request closed without merging**
