### PR TITLE
New field in res.partner to know if a partner is national or international

### PR DESCRIPTION
**Pull request by yaniaular**
- New partner_foreign module to know if a partner is national or international based in company location

### CODE REVIEW

**Comment by nhomar** [comment]
@yaniaular nombra el módulo:

partner_foreign, partner_location es más para geolocalización es un poquito confuso.

**Comment by yaniaular** [comment]
@nhomar Ok.

**Comment by yaniaular** [comment]
@nhomar  can you merge this please?

**Comment by yaniaular** [comment]
@nhomar Wait.... Checking runbot...

**Comment by yaniaular** [comment]
@nhomar Runbot: http://runbot.vauxoo.com/runbot/build/47542
and travis is ready. There are errors unrelated to development presented in this merge.

Ready to merge

**Pull request merged**
