### PR TITLE
[ADD] product_extended_segmentation_byproduct: Added the segmented co… task#31736

### PR DESCRIPTION
**Pull request by keylor2906**
…st calculation with sub products done in the same bom (byproducts)

### CODE REVIEW

**Comment by sabrinagnu** [comment]
I need please a Vo. Bo. here @JulioSerna @hbto

**Comment by sabrinagnu** [comment]
@JulioSerna @hbto this will not be merged without unit tests but by the moment is on hold, but I would like your review already or if you have something against this way to go, FYI functionally LGTM.

**Review by hbto — COMMENTED** [review]
Could you please add a Video where:
- There is a product without subproduct involved, and
- Thre is a product with subproduct involved.

Regards

**Comment by keylor2906** [comment]
@dsabrinarg Unitests added.

**Comment by sabrinagnu** [comment]
@hbto brief functional video in a lodi environment https://youtu.be/sURCdEGxNx4

**Comment by sabrinagnu** [comment]
@hbto same functional behavior for 11.0 https://git.vauxoo.com/vauxoo/quebec/merge_requests/33

**Comment by hbto** [comment]
:+1:

**Pull request merged**
