### PR TITLE
[9.0][ADD] new module currency_print_name

### PR DESCRIPTION
**Pull request by osvalr**
##  Summary
When needing to print invoices, POS tickets, sale orders or any printed document and also indicate the full name in your or your partner's language for the currency you're handling, this module includes that and makes it translatable getting up to 50 characters in the print name long enough for your needs.

### CODE REVIEW

**Comment by osvalr** [comment]
Hi @josemoralesp would you help me to review this new module, your feedback is welcome

**Comment by osvalr** [comment]
@nhomar your feedback is welcomed here

**Comment by nhomar** [comment]
I think we need the es.po file.

**Comment by osvalr** [comment]
@nhomar `es.po` is already there

**Pull request closed without merging**
