### PR TITLE
[FIX] website_sale: ERR403, now 'Also purchased' section renders only website_published=True products.

### PR DESCRIPTION
**Pull request by oscarolar**

### CODE REVIEW

**Comment by oscarolar** [comment]
https://github.com/Vauxoo/yoytec/pull/198

**Comment by moylop260** [comment]
Please, Could you add unittest to increase the coveralls in this module?

**Comment by moylop260** [comment]
We have next coverage:
addons-vauxoo/website_customer_also_purchased/model/product.py
Percent coverage: 29%
Without test: 39-71
Please, Could you Increase it >60

**Comment by moylop260** [comment]
coverage 100% WTF :neckbeard:



:+1:  :+1:  :+1:  @oscarolar Thanks!

**Comment by oscarolar** [comment]
Welcome bro @moylop260

**Pull request merged**
