### PR TITLE
[IMP] .travis.yml: enable Runbot t#54296

### PR DESCRIPTION
**Pull request by luisg123v**
`.travis.yml` file is modified to use variables defined in the
`variables.sh` file.

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 could you review, please?

**Comment by moylop260** [comment]
LGTM

👍 

🥳

**Comment by moylop260** [comment]
Could you add the Runbot's badge to README, please?

**Comment by luisg123v** [comment]
@moylop260 done, badge added.

**Pull request merged**
