### PR TITLE
[REF] show parent categories with product HU#977, CA#11, TASK#4335

### PR DESCRIPTION
**Pull request by hugho-ad**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@oscarolar Me apoyas con un +1,
dummy pr https://github.com/Vauxoo/yoytec/pull/327

**Comment by oscarolar** [comment]
:+1:

**Comment by oscarolar** [comment]
Please fix the 

```
Public Category view
```

**Comment by hugho-ad** [comment]
@oscarolar Done:
dummy pr https://github.com/Vauxoo/yoytec/pull/327

**Comment by hugho-ad** [comment]
@oscarolar this pnr is ready to be merged

**Comment by oscarolar** [comment]
:+1:

**Comment by hugho-ad** [comment]
@moylop260 can you merge this please.

**Pull request merged**
