### PR TITLE
[ADD] stock_allow_past_date: Modified select fixed dates and make the unit test taking into account this date

### PR DESCRIPTION
**Pull request by deivislaya**
This PR is referenced to issue Vauxoo/yoytec#1421

### CODE REVIEW

**Comment by hugho-ad** [comment]
@deivislaya this change has a Dummy Pr ?

**Comment by hugho-ad** [comment]
FYI

``` python
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:47:37: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:47:39: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:47:41: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:47:44: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:54:37: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:54:39: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:54:41: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:54:44: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:61:37: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:61:39: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:61:41: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:61:44: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:69:37: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:69:39: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:69:41: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:69:44: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:70:46: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:70:48: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:70:50: E231 missing whitespace after ','
/home/travis/build/Vauxoo/addons-vauxoo/stock_allow_past_date/tests/test_past_date.py:70:53: E231 missing whitespace after ','
```

**Comment by zaoral** [comment]
Hi @deivislaya 
Please fix the lint errores and create a dummy pr
Please do not forget to link you dummy pr in yoytec to his PR

Best Regards

**Comment by zaoral** [comment]
Thank you for the feedback @hugho-ad

**Comment by luisg123v** [comment]
This is abandoned and Yoytec is not a customer anymore, so closing.

**Pull request closed without merging**
