### PR TITLE
[ADD][sale_order_create_task_planned_hours] adds Estimated hours that helps to calculate the planned hours when the tasks are created

### PR DESCRIPTION
**Pull request by hugho-ad**
[TASK#3715](https://www.vauxoo.com/?ts=1431964945372#id=3715&view_type=form&model=project.task&action=778)
[HU#862](https://www.vauxoo.com/#id=862&view_type=form&model=user.story)
This module adds a field in the lines of Sale order, (Estimated hours) that helps to calculate the planned
hours when the tasks are created

### CODE REVIEW

**Comment by hugho-ad** [comment]
@JulioSerna , can you help me with a review/ +1 please.

**Comment by JulioSerna** [comment]
:+1:

**Comment by hugho-ad** [comment]
@dsabrinarg , this pr is ready to review/merge

**Comment by sabrinagnu** [comment]
@hugho-ad :+1: solo esperemos las pruebas del cliente antes de hacer el merge.

**Comment by hugho-ad** [comment]
@dsabrinarg Todo verde

**Pull request merged**
