### PR TITLE
[IMP] product_pricelist_report_qweb: Added option to only print registers that have an amount in the price column

### PR DESCRIPTION
**Pull request by luistorresm**
This new parameter is set in the wizard that call report.
Added test to new changes

### CODE REVIEW

**Comment by luistorresm** [comment]
@hbto 

Could you check this PR please?

I was added a new boolean to indicate that only must be print registers with price.

The customer authorized this changed.

Dummy PR:
https://github.com/Vauxoo/wohlert/pull/55

New field:
https://drive.google.com/a/vauxoo.com/file/d/0B8glieilJ0dnTzB4aWVxVlo0ZVE/view?usp=drivesdk

Runbot:
runbot repo vauxoo s ci

**Comment by hbto** [comment]
@luistorresm 

Checking

**Comment by hbto** [comment]
+1 @luistorresm 

It can be merged

@nhomar @moylop260 @dsabrinarg

**Comment by moylop260** [comment]
:+1:

**Pull request merged**
