### PR TITLE
[REF] product_unique_default_code: Remove overwrite of original data demo. Fix test and pep8

### PR DESCRIPTION
**Pull request by moylop260**
*Before, the "default code" of product is duplicated from original data demo in one product.
But with this pr now we don't have this problem https://github.com/odoo/odoo/pull/5142
Then, now is deprecated the overwrite of data demo from "product_unique_default_code" module.

*Fix test

### CODE REVIEW

**Comment by moylop260** [comment]
This PR depends of https://github.com/odoo/odoo/pull/5236

**Comment by nhomar** [comment]
@moylop260 Is this still valid? or can I clos this PR?

**Comment by moylop260** [comment]
@nhomar 
I closed this PR because next PR's fixed this case:
https://github.com/odoo/odoo/pull/5142
https://github.com/odoo/odoo/pull/5414

**Comment by moylop260** [comment]
...ahh and this one: https://github.com/odoo/odoo/pull/5236

**Pull request closed without merging**
