### PR TITLE
[REM] *: Remove uninstallable modules

### PR DESCRIPTION
**Pull request by luisg123v**
Most of the modules are not installable, they come from previous
versions and were never migrated.

This removes all those, 307 in total.

The complete list of removed modules may be checked [here](https://github.com/Vauxoo/addons-vauxoo/files/5202926/deleted_modules.txt)

### CODE REVIEW

**Comment by luisg123v** [comment]
@hugho-ad @moylop260 @hbto 

Could you review, please?

CC @JulioSerna @dsabrinarg @CarmenMiranda

**Comment by moylop260** [comment]
This is a old matter
Please, confirm with @nhomar 
IMHO we shouldn't make these kind of changes in branches <=11.0 since that it will be deprecated soon.

**Comment by nhomar** [comment]
@luisg123v 

This version will not be mainatined anymore in 1 month

**Comment by hbto** [comment]
@moylop260 & @nhomar Yet this version won't die overnight and it will be still be used by some customers thus the cleaning is still neeeded.

Regards.

**Comment by luisg123v** [comment]
@moylop260 and @nhomar 

In addition, this already forced us to rollback a deployment into production due to conflicts (see https://github.com/Vauxoo/addons-vauxoo/pull/1445), so we don't want this to happen again.

**Comment by moylop260** [comment]
@luisg123v 
I got it

The main description of this PR is not justify the reason of #1445 

Could you explain it better since that you have a good point?

**Comment by luisg123v** [comment]
I've meet with @nhomar, @hugho-ad and @carlosrve regarding this.

We accorded that all changes performed to branches from 11.0 will be reverted, to keep it's stability and to follow a guideline (unknown to most of us so far) that only the two latest version will be actively maintained, and the oldest one only until january of the year Odoo dropps support for it.

An email will be sent informing the above.

**Pull request closed without merging**
