### PR TITLE
[FIX] internal_transfer_with_agreed_amount: fix README images reference path t#71297

### PR DESCRIPTION
**Pull request by CLaurelB**
This update corrects the path to the images in the README, ensuring they are displayed properly.

### CODE REVIEW

**Comment by luisg123v** [comment]
Where aren't they being displayed correctly? Did you check this works also on GitHub?

**Comment by CLaurelB** [comment]
@luisg123v 

> Where aren't they being displayed correctly? Did you check this works also on GitHub?

It is the same issue as in portal_multicurrency_totals. They are not being displayed correctly on GitHub.

Related commit: https://github.com/Vauxoo/addons-vauxoo/commit/dec8032ae8b4da554d341e4f4b21334c031d97ca

**Comment by CLaurelB** [comment]
@luisg123v could you review, please?

**Review by luisg123v — APPROVED** [review]
LGTM :+1:

**Pull request merged**
