### PR TITLE
[MIG] account_bank_reconcile_transfer: Migrate to v15.0 T#59105

### PR DESCRIPTION
**Pull request by rolandojduartem**
This module lets create the internal transfers from the statement line
directly with no extra steps, reconciling their journal entries.

Changelog:
- 'process_reconciliation' was refactored and renamed to 'reconcile' by
[1]
- Now, '_prepare_reconciliation' method is inherited because it returns
the correct values to create the internal transfer.

**Send:**

Screenshot from 2022-10-25 12-36-48

Screenshot from 2022-10-25 12-37-09

Screenshot from 2022-10-25 12-45-39

Screenshot from 2022-10-25 12-45-52

**Receive:**

Screenshot from 2022-10-25 12-36-31

Screenshot from 2022-10-25 13-34-27

Screenshot from 2022-10-25 12-45-06

Screenshot from 2022-10-25 12-45-17

Reference:

[1] https://github.com/odoo/odoo/commit/caeb782841fc5a7ad71a196e2c9ee67644ef9074

### CODE REVIEW

**Comment by rolandojduartem** [comment]
Hi, @tomeyro, please, may you leave me your feedback testing this PR? This PR is in draft state.

cc @luisg123v  @desdelinux @nhomar

**Comment by rolandojduartem** [comment]
Sorry, a typo was fixed.

**Comment by rolandojduartem** [comment]
@tomeyro friendly reminder.

**Comment by tomeyro** [comment]
@rolandojduartem It correctly creates the transfer (payment in and out), but it seems the reconcile process is not fully completed.

I noticed that the payment didn't have a link to the bank statement, which appears after reconciling a payment to a bank statement line.



Then I reverted the reconciliation and reconciled again by selecting the payment manually.

(Note that I used that 'last year insterests' line from the demo data for the example)



And then the button to the statement appears on the payment.



Please check that. The rest of the process seems to be working as expected.

**Comment by rolandojduartem** [comment]
@tomeyro, I updated this PR, if you can, your feedback is very welcome. As you can see in the picture in the description, the process is working very well.

cc @luisg123v @desdelinux

**Comment by tomeyro** [comment]
@rolandojduartem @luisg123v LGTM

**Comment by rolandojduartem** [comment]
Closed because it was migrated on other repository

**Pull request closed without merging**
