### PR TITLE
[FIX] website_product_comment_purchased: Fix yoytec issue #1047

### PR DESCRIPTION
**Pull request by gomezvillegasdaniel**
FIXES: https://github.com/Vauxoo/yoytec/issues/1047
DUMMY: https://github.com/Vauxoo/yoytec/pull/1054

Before:
captura de pantalla 2016-04-14 a las 5 42 58 p m

After:
captura de pantalla 2016-04-14 a las 5 57 16 p m

### CODE REVIEW

**Comment by gomezvillegasdaniel** [comment]
This is the error travis throws
captura de pantalla 2016-04-14 a las 4 12 12 p m

**Comment by gomezvillegasdaniel** [comment]
@oscarolar I've done with this but I got only this error.
e874bbe2-025b-11e6-9cc5-3c785946a2cf

**Comment by gomezvillegasdaniel** [comment]
captura de pantalla 2016-04-15 a las 4 07 10 p m

**Comment by oscarolar** [comment]
Yeah, you have to migrate the fields to API V8 in order to fix that error

**Comment by gomezvillegasdaniel** [comment]
@oscarolar here is the reason for this code has not been migrated to v8 yet
https://www.youtube.com/watch?v=-RcrjbLturE

**Comment by oscarolar** [comment]
Dude, your dummy is pointless, the dummy PR must be done in the customer repo.

**Pull request merged**
