### PR TITLE
[IMP] default_warehouse_from_sale_team: defined 'picking_type_id'

### PR DESCRIPTION
**Pull request by JulioSerna**
default as well from the sale team werahouse

### CODE REVIEW

**Comment by nhomar** [comment]
@JulioSerna can you add  a test for your new method please?

**Comment by JulioSerna** [comment]
@nhomar 
Test done
and the PR will be tested in this [DUMMY](https://github.com/Vauxoo/yoytec/pull/1811)

**Comment by nhomar** [comment]
@JulioSerna can you point me out the User Story and/or the explanation/use case about this? it is so light the explanation you share here and I do not understand at first view why this is needed.

**Comment by JulioSerna** [comment]
@nhomar 

it is about the [HU#1129](https://www.vauxoo.com/web#id=1552&view_type=form&model=project.issue&action=578)
And the [Issue#1552](https://www.vauxoo.com/web#id=1552&view_type=form&model=project.issue&action=578)

When user make a purchase order the picking type must be one related to sale team warehouse

**Pull request merged**
