### PR TITLE
[MIG] Migration to v12.0

### PR DESCRIPTION
**Pull request by luiseevaquer**
**Modules to migrate:**

- [x]  account_analytic_policy
- [x]  account_anglo_saxon_stock_move
- [ ]  account_anglo_saxon_stock_move_purchase
- [ ]  account_anglo_saxon_stock_move_sale
- [ ]  account_asset_date
- [x]  account_asset_move_check
- [x]  account_currency_tools
- [x]  account_invoice_line_asset_category_required
- [x]  account_move_line_production
- [x]  default_warehouse_from_sale_team 
- [x]  mrp_force_responsible
- [x]  mrp_routing_account_journal
- [x]  mrp_workcenter_account_move
- [x]  mrp_workcenter_segmentation
- [x]  product_extended_segmentation
- [x]  product_extended_segmentation_byproduct
- [x]  purchase_third_validation
- [x]  stock_by_warehouse 
- [x]  stock_cost_segmentation 
- [x]  stock_deviation_account 
- [x]  stock_landed_segmentation 
- [x]  stock_move_entries

### CODE REVIEW

**Comment by hugho-ad** [comment]
FYI @moylop260

**Comment by moylop260** [comment]
Is it wip, right?

**Comment by hugho-ad** [comment]
No anymore

**Comment by hugho-ad** [comment]
thank you @moylop260

**Pull request merged**
