### PR TITLE
[IMP] Flattening method compute_price

### PR DESCRIPTION
**Pull request by hbto**
Only a almost improve on code

### CODE REVIEW

**Comment by hbto** [comment]
@josemoralesp Could you please check and provide any feedback,
Best Regards.

**Comment by moylop260** [comment]
@hbto 
Could you add "the dummy PR", please?

**Comment by hbto** [comment]
@moylop260 Where do you want the Dummy pr

**Comment by hbto** [comment]
https://github.com/Vauxoo/lodigroup/pull/287/files

**Comment by hbto** [comment]
Failures in CI/Runbot are unrelated to this PR

**Comment by hbto** [comment]
@moylop260 @josemoralesp Can you confirm?

Best Regards.

**Comment by moylop260** [comment]
@josemoralesp 
Can we merge it?

**Pull request merged**
