### PR TITLE
[DEL] cost_imex: In favor of landed cost, this module will not be used anymore since v8.0.

### PR DESCRIPTION
**Pull request by KarenKawaii**
### [VX#4604](https://www.vauxoo.com/web#id=4604&view_type=form&model=project.task&action=138)
- [x] Delete Module `cost_imex` deprecated by `landed_cost`.

### CODE REVIEW

**Comment by nhomar** [comment]
@KarenKawaii please remove completelly this module, in favor of landed cost, thi module will not be used anymore since v8.0 (put this commnt as reference in the commit please).

I will not merge this and just push again with the removal and change the PR title.

Regards.

**Comment by KarenKawaii** [comment]
@nhomar module deleted.

**Comment by nhomar** [comment]
@hbto can you give your blessing here?

**Comment by hbto** [comment]
+1
Get rid of it.

**Pull request merged**
