### PR TITLE
  [ADD] New module that allows the user to rate a product with the classic stars.

### PR DESCRIPTION
**Pull request by oscarolar**
[ADD] New module that allows the user to rate a product with the classic stars.

### CODE REVIEW

**Comment by moylop260** [comment]
@oscarolar 
Puedes poner el título de este pr, como si fuera un msg commit.

**Comment by oscarolar** [comment]
Done.

**Comment by nhomar** [comment]
@oscarolar Relate the PR to User Story number/task/issue please?

**Comment by oscarolar** [comment]
Nhomar here is the [HU](https://www.vauxoo.com/#id=365&view_type=form&model=user.story&menu_id=557&action=726), comment and merge if its possible please.

**Pull request closed without merging**
