### PR TITLE
[REF] stock_location_code: Revert to original warehouse value, because other customer use this way

### PR DESCRIPTION
**Pull request by moylop260**
This changed by the following comment: https://github.com/Vauxoo/addons-vauxoo/pull/929#issuecomment-219173136 based on HU#962 - CA#5

But this module is used with other customer and need the previous way.

Result: [barcode] name (warehouse)
screen shot 2016-05-23 at 12 21 28 pm

Result of tests:
screen shot 2016-05-23 at 12 23 08 pm

The real diff `git diff vauxoo/8.0..vauxoo-dev/8.0-ref-location-get-name-moy` is:

``` diff
diff --git a/stock_location_code/model/stock.py b/stock_location_code/model/stock.py
index cbd935c..4a2b260 100644
--- a/stock_location_code/model/stock.py
+++ b/stock_location_code/model/stock.py
@@ -46,7 +46,8 @@ class StockLocation(models.Model):
     _inherit = 'stock.location'

     # barcode is between [] e.g. "[1234] location1"
-    barcode_re = re.compile(r'\[(?P<barcode>.*?)\]')
+    barcode_re = re.compile(r'^\[(?P<barcode>.*?)\]')
+    warehouse_re = re.compile(r' \((?P<wh>.*?)\)$')

     @api.model
     def name_search(self, name, args=None, operator='ilike', limit=100):
@@ -59,6 +60,7 @@ class StockLocation(models.Model):
             barcode = re_search.group('barcode') if re_search else name
             recs = self.search([('loc_barcode', '=', barcode)] + args,
                                limit=limit)
+            # TODO: Search by warehouse too with self.warehouse_re
         res = recs.name_get() or super(StockLocation, self).name_search(
             name, args=args, operator=operator, limit=limit)
         return res
@@ -70,7 +72,14 @@ class StockLocation(models.Model):
         concatenates the code and warehouse to a location if they exist.
         Visually, it's better to know which owns the warehouse location.
         """
-        name = super(StockLocation, self)._name_get(location)
         barcode = "[%(barcode)s]" % {'barcode': location.loc_barcode} \
             if location.loc_barcode else ''
-        return barcode + ' ' + name if barcode else name
+        # TODO: Add fields.function to get warehouse. get_warehouse is too slow
+        # TODO: Add a parameters for a location path name or a wh_name
+        warehouse = self.env['stock.warehouse'].browse(
+            self.get_warehouse(location))
+        wh_name = "(%(warehouse)s)" % {'warehouse': warehouse.name} \
+            if warehouse else ''
+        items = [barcode.strip(), location.name.strip(), wh_name.strip()]
+        new_name = ' '.join(item for item in items if item)
+        return new_name
```

### CODE REVIEW

**Comment by moylop260** [comment]
@dsabrinarg 
Could you check it?

@gquilarque 
Read the main description please.

**Comment by gquilarque** [comment]
@moylop260 Roger that.

**Comment by sabrinagnu** [comment]
@moylop260 Sure, here is the DUMMY for Lodi https://github.com/Vauxoo/lodigroup/pull/558

**Comment by moylop260** [comment]
@dsabrinarg 
The original one was: https://github.com/Vauxoo/lodigroup/pull/557

But the travis and runbot is out by github issues.

I added image of result of tests and the functional tests...

**Comment by moylop260** [comment]
Then I will merge it in order to expedite

**Comment by sabrinagnu** [comment]
👍  thanks @moylop260

**Pull request merged**
