### PR TITLE
[ADD] stock_picking_log_message_transfer module added for A message i…

### PR DESCRIPTION
**Pull request by yaniaular**
…n log when the products is transfered.

[HU # 985](https://www.vauxoo.com/web?db=vauxoo#id=985&view_type=form&model=user.story)
CA # 5

mensaje en el log

### CODE REVIEW

**Comment by yaniaular** [comment]
@gquilarque Please review

**Comment by yaniaular** [comment]
Dummy PR https://github.com/Vauxoo/yoytec/pull/279

**Comment by gquilarque** [comment]
@yaniaular please put only "Albarán Transferido"  because the author is already in the message footer.

Thank you for the screenshot.

**Comment by yaniaular** [comment]
@gquilarque ready to merge

**Comment by moylop260** [comment]
@yaniaular 
pr dummy?

**Comment by moylop260** [comment]
https://github.com/Vauxoo/yoytec/pull/279
?

**Comment by moylop260** [comment]
PR with tests, green coveralls in dummy pr, green runbot in dummy pr, green travis in dummy pr, use of image in description of this pr...
Good job! :+1:

**Pull request merged**
