### PR TITLE
ADD: This module allows Inventory valuation when product type is Stockable Product and Consumible

### PR DESCRIPTION
**Pull request by jorgenaranjoVauxoo**
Tarea del desarrollo
https://www.vauxoo.com/web#id=3817&view_type=form&model=project.task&menu_id=136&action=138

### CODE REVIEW

**Comment by nhomar** [comment]
@jorgenaranjo Can you add an unit test for this please in order to be sure that all the elements involved in the valuation are right.

@hbto Can you design the test with @jorgenaranjo please.

**Comment by nhomar** [comment]
@hbto Is this yet needed? if yes, take care of this please (trace the task information)

**Comment by hbto** [comment]
So far no longer needed, 

if need arises then I will take back this PR

**Comment by nhomar** [comment]
I wil not delete the branch just in case.

**Pull request closed without merging**
