### PR TITLE
[MIG] stock_by_warehouse_purchase: Migration to 16.0 T#63809

### PR DESCRIPTION
**Pull request by rolandojduartem**
**Before recompute:**

Screenshot from 2023-03-17 16-44-13

**After recompute:**

Screenshot from 2023-03-17 16-42-59

### CODE REVIEW

**Comment by rolandojduartem** [comment]
Hi, @luisg123v could you review this migration? this PR goes after [!1602](https://github.com/Vauxoo/addons-vauxoo/pull/1602)

cc @desdelinux

**Comment by rolandojduartem** [comment]
@desdelinux, for the functional review, you could use the runbot on https://git.vauxoo.com/vauxoo/dhm/-/merge_requests/131

**Review by luisg123v — APPROVED** [review]
LGTM :+1: 

Just waiting for #1602 to merge this one

**Review by desdelinux — APPROVED** [review]
Functional Review is ok

cc @rolandojduartem @luisg123v @hugho-ad

**Comment by rolandojduartem** [comment]
@luisg123v rebased!

**Comment by luisg123v** [comment]
@rolandojduartem coverage is decreasing with each of these merges, it's already below the minimum allowed threshold.

I'm merging this for now, but you need to implement small tests to cover the missing lines

**Pull request merged**
