### PR TITLE
[REM] Remove deprecated modules

### PR DESCRIPTION
**Pull request by moylop260**
invoice_cancel_islr
account_move_line_address
stock_purchase_expiry
bank_iva_report
recovery_attachments_bd
mrp_webkit_report_wizard
invoice_multicompany_report
partner_property_accounts
purchase_multi_report
mrp_bom_subproduct_cost
issue_view

### CODE REVIEW

**Comment by moylop260** [comment]
@hbto and @nhomar 
feedback, or approval please

**Comment by nhomar** [comment]
Hubiese sido bueno un pr por modulo removido pero fino estamos seguros no se esta borrando nada raro no?

**Comment by zaoral** [comment]
Tengo duda con el modulo stock_purchase_expiry. Este se borra porque no
funciona en v8? Si es asi el contenido de la descripcion se puede pasar al
branch en v7. Estan de acuerdo @nhomar @hbto @moylop260

**Comment by nhomar** [comment]
@moylop260 you did this job some time ago, can you please try to check this in the frame of other fixes already done?

**Comment by moylop260** [comment]
I close this issue because we are working in task vx#4604 to split PR by module.

**Pull request closed without merging**
