### PR TITLE
[MERGE] forwardporting from vauxoo/7.0

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by nhomar** [comment]
@moylop260 thi PR is bringing red on runbot for oml-v2 @JulioSerna can you help me to verify why?

**Comment by nhomar** [comment]
@moylop260 this is the runbot:

[runbot](http://runbot.vauxoo.com/runbot/team/oml-v2-28#50pull_306)

**Comment by JulioSerna** [comment]
@nhomar @moylop260 
This is missing execute `git pull 8.0`

**Comment by moylop260** [comment]
@JulioSerna 
You are right!
Thank you
I executed `git pull 8.0`now!

**Comment by moylop260** [comment]
@nhomar 
Now runbot is green!

**Pull request merged**
