### PR TITLE
 [MIG] account_currency_tools: v8.0 -> v11.0 task#34299

### PR DESCRIPTION
**Pull request by keylor2906**

### CODE REVIEW

**Comment by keylor2906** [comment]
@dsabrinarg Could you please review this?

The dev instance is: http://dev.lodigroup.com:30013

Dummy MR: https://git.vauxoo.com/vauxoo/lodi/merge_requests/127

image

image

**Comment by sabrinagnu** [comment]
@hbto may you please give me your +1 here?.

**Comment by hbto** [comment]
@dsabrinarg Functionally I approve this PR.

What are the reds related to?

Regards

**Comment by sabrinagnu** [comment]
@hbto successful functional tests today, may you please merge? the red is very old on the 11.0 branch.

**Pull request merged**
