### PR TITLE
[ADD]website_varians_extra: printable layout and print btn.

### PR DESCRIPTION
**Pull request by gmlp**
BUILD: https://github.com/Vauxoo/yoytec/pull/859

screenshot from 2016-03-14 10-52-23
)

### CODE REVIEW

**Comment by gmlp** [comment]
@oscarolar, any thoughts?

**Comment by nhomar** [comment]
@gmlp in the HU and CA related is not the explanation of where you need to take teh format?

review origina http://www.yoytec.com and see that result it must be shown on that way.

**Comment by gmlp** [comment]
@nhomar, the format must be the same?
screenshot from 2016-03-10 23-31-53

**Comment by nhomar** [comment]
On Thu, Mar 10, 2016 at 11:34 PM, gmlp notifications@github.com wrote:

> @nhomar https://github.com/nhomar, the format must be the same?

Yes at least the V1.

and NOT printing the website.

You must create a report which will be called using an URL: like this:

https://www.odoo.com/documentation/9.0/reference/reports.html

look for "Reports are Web Pages."

## 

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by gmlp** [comment]
@nhomar, done.

**Comment by oscarolar** [comment]
@gmlp good job please address the following details on the screnshot:
scr

and also please add translations for `es_PA`

**Comment by gmlp** [comment]
@oscarolar :Done. 

screenshot from 2016-04-04 22-30-07

**Pull request merged**
