### PR TITLE
[ADD] product_available_by_warehouse: add field to show qty by wh

### PR DESCRIPTION
**Pull request by suniagajose**
## Summary

This module provide a field in sale order line to show a message with product availability by warehouse. Also propose routes with qty > 0.0
## Preview

img1

img2

img3

### CODE REVIEW

**Comment by suniagajose** [comment]
Hi @JulioSerna 

This is the feature that we talk about, please give me your feedback... thanks

**Comment by JulioSerna** [comment]
LGTM
@suniagajose 
👍

**Comment by JulioSerna** [comment]
@suniagajose 

There is one error when there is no product, reported by @omejia26

**Comment by JulioSerna** [comment]
`File "/root/addons-vauxoo/product_available_by_warehouse/models/sale.py", line 54, in product_id_change_with_wh get_product_available_by_warehouse()[product.id][colname] KeyError: False`

**Comment by suniagajose** [comment]
ok @JulioSerna let me fix it

**Comment by suniagajose** [comment]
ready @JulioSerna, already solved the error when there no product.

Additionally i did a onchange in 'Show Message' field

**Comment by JulioSerna** [comment]
@nhomar 

Could you merge this pr?

**Comment by nhomar** [comment]
where is a dummy PR?

I do not like too much the usability, I think this musy be a feature in the normal product list view and then reuse it when dneeded because this will be necessary in several places.,

**Comment by nhomar** [comment]
I can merge it if needed for tests but We should rethink this.

**Comment by nhomar** [comment]
in the travis there are lint problems, can you check if can or can not be ignored?

**Pull request merged**
