### PR TITLE
[MIG] web_widget_json_graph: migration to 12.0

### PR DESCRIPTION
**Pull request by luisg123v**

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 @hugho-ad @frahikLV 

could you review, please?

I'm migrating this module from the web repo, because that module was actually never in the OCA, so ours is diverging without needing to.

**Comment by hugho-ad** [comment]
why not post it at oca/web?

**Comment by luisg123v** [comment]
@hugho-ad because it has never belonged there.

It could be added, but it would be a new module.

**Comment by hugho-ad** [comment]
@luisg123v 

>>It could be added, but it would be a new module.
New module name?

I think this we should move it there, at oca/web

**Comment by luisg123v** [comment]
@hugho-ad same module name, but new module for the OCA

**Comment by moylop260** [comment]
I think It is not a bad idea to move this module to OCA

**Comment by luisg123v** [comment]
@moylop260 @hugho-ad PR to the OCA created: https://github.com/OCA/web/pull/1733. Authorship has been taken care of.

I'm closing this one.

**Pull request closed without merging**
