### PR TITLE
[IMP] account_move_report: Add names to XML elements

### PR DESCRIPTION
**Pull request by luisg123v**
This is to be able to inherit the report on a deterministic manner.

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 @hbto @hugho-ad,

Could you review, please?

**Review by hugho-ad — APPROVED** [review]
LGTM :+1: 
Changes in order to make report more inheritable

**Review by moylop260 — APPROVED** [review]
👍

**Comment by moylop260** [comment]
Do you have a dummy MR?

**Comment by luisg123v** [comment]
No, but I need this for the migration of vauxoo. Without this, I'm not able to install the module vauxoo, and I managed to install it with this..

**Comment by moylop260** [comment]
> Without this, I'm not able to install the module vauxoo

So, Can you create a dummy to vx instance?

In order to check that with this you are able to install the module vauxoo.

Is not?

**Comment by luisg123v** [comment]
FYI AFAIK this module is not used yet in v13, it was migrated straight to 14.0. When I re-initialized the branches 13.0 & 14.0, I followed the standard migration process and migrated it to v13 and re-migrated it to v14 (on https://github.com/Vauxoo/addons-vauxoo/pull/1455 and https://github.com/Vauxoo/addons-vauxoo/pull/1456, respectively).

**Comment by moylop260** [comment]
I didn't get you but the MR looks safe for me

So, you can merge it if you consider it

**Comment by hbto** [comment]
no vx instance in 13.0

only vx instance in 14.0

@Moises Lopez Vauxoo <moylop260@vauxoo.com>

Regards.
Quien suscribe,

Humberto Arocha

**Comment by hbto** [comment]
> > Without this, I'm not able to install the module vauxoo
> 
> So, Can you create a dummy to vx instance?
> 
> In order to check that with this you are able to install the module vauxoo.
> 
> Is not?

@luisg123v I would suggest to use a v13.0 project to make a dummy.

Regards.

**Comment by luisg123v** [comment]
[here](https://git.vauxoo.com/vauxoo/instance/-/merge_requests/1156) the MR where I managed to install this module. Pay attention to the last commit, which is the dummy one.

**Comment by luisg123v** [comment]
As @moylop260 commented, this change is safe enough, and it's working on the dummy MR. So I'll merge it.

**Pull request merged**
