### PR TITLE
[IMP] Add the chance to use mrp.unbuild stock.move records. - Issue13718

### PR DESCRIPTION
**Pull request by hbto**

### CODE REVIEW

**Comment by belisac** [comment]
Hello @hbto 

+1

Please @luisg123v could you review and merge the change please! 

Thanks in advance!

**Review by luisg123v — APPROVED** [review]
Could you edit the commit title to conform our standars? Is specially useful in repos like this one, where we maintain a lot of modules.

Something like: 
`[IMP] stock_landed_costs_average: ...`

Other than that LGTM.

**Comment by hbto** [comment]
> Could you edit the commit title to conform our standars? Is specially useful in repos like this one, where we maintain a lot of modules.
> 
> Something like:
> `[IMP] stock_landed_costs_average: ...`
> 
> Other than that LGTM.

Changes were done

**Comment by luisg123v** [comment]
Hi @hbto,

Are extra commits introduced in last push intentional?

**Review by luisg123v — APPROVED** [review]

**Pull request merged**
