### PR TITLE
8.0 hu#979 crm claim summary report osval

### PR DESCRIPTION
**Pull request by osvalr**
Add report for crm claims that summarizes products claims printing one for customer and another one for  internal support

Things to do:
- [X] Header
- [X] Customer and Internal copies footer notes
- [x] Translate based on partner language
- [x] Place rma footer note
- [x] Customer Name, Email and Delivery Address in the Same column and make the column wider
- [x] Fix colon is missing at the end of Claim Date
- [x] Reduce the distance between the label and value, so it will be more space to take advantage on.
- [x] It is required to have a translatable footer
- [x] Label for product on claims
- [x] Unit test

the final result for this report is at least three images as following

Customer Copy

Internal Support

Labels to be attached to products under claim

### CODE REVIEW

**Comment by osvalr** [comment]
Hi @nhomar,

I've added tests, please review it

**Comment by yaniaular** [comment]
@osvalr please, put here the link to PR of yoytec with dependence to this report.

**Comment by osvalr** [comment]
This report is a dependency for modules **`yoytec`** and **`yoytec_customer_rma_workflow`** and that proposal is located https://github.com/Vauxoo/yoytec/pull/211

**Comment by osvalr** [comment]
@nhomar i've updated this PR's description to show how the report is rendered

**Comment by osvalr** [comment]
@josemoralesp @yaniaular please help me out to review this proposal

**Pull request merged**
