### PR TITLE
[REF] add a default to field check_inv_pick in sale.order and stock.picking

### PR DESCRIPTION
**Pull request by hugho-ad**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@gquilarque aquí esta la pr dummy:https://github.com/Vauxoo/yoytec/pull/329

los modulos de rma, en su data/demo si crean algunas SO para posterior mente hacer los tranfer correspodientes, con lo que fallaran si se pone el default en modelo de SO:https://github.com/vauxoo-dev/addons-vauxoo/blob/8.0-stock-pic-inv-vali/stock_picking_invoice_validation/model/sale_order.py#L21

**Comment by moylop260** [comment]
@hugho-ad 
Please, Could you set `check_invoice = False` to sales created from `yoytec_customer_rma_workflow`?

**Comment by moylop260** [comment]
@hugho-ad 
Could you change the ondelete='cascade' to ondelete='set null'
and set the string of picking.invoice_id to "Factura verificada" with readonly=True

**Comment by hugho-ad** [comment]
@moylop260 , para que los test superen las pruebas debo modificar la data/demo de los siguietes:

``` python
"stock_picking_log_message_transfer",
"crm_rma_lot_mass_return",
"yoytec_customer_rma_workflow",
```

**Comment by moylop260** [comment]
+1

**Comment by hugho-ad** [comment]
@moylop260 this the rma pr https://github.com/Vauxoo/rma/pull/77

Yanina puts some comments, read them  and let me know what do you think?

**Comment by hugho-ad** [comment]
@moylop260 this pr is ready to merge.

The default in  saler.order will be done in next pr https://github.com/Vauxoo/yoytec/pull/355

**Pull request merged**
