### PR TITLE
8.0 stock landed costs average optimization hbto

### PR DESCRIPTION
**Pull request by hbto**

### CODE REVIEW

**Comment by hbto** [comment]
@nhomar could you check these changes?

**Comment by nhomar** [comment]
@hbto did you made a dummy in the related repo? it looks fine all your changes.

**Comment by nhomar** [comment]
@hbto I saw the PR DUMMY, Next time add a link to avoid stupid questions on our side. :-)

**Comment by hbto** [comment]
Got it

**Pull request merged**
