### PR TITLE
[IMP] stock_card: adapt card to get price average per warehouse

### PR DESCRIPTION
**Pull request by JulioSerna**
TODO:
- [ ] add wareohuse_id fields to wizard,
  stock card generate odoo
- [ ] if warehouse is empty make the native process
- [ ] if warehouse is set fill `location_ids` getting from warheouse

### CODE REVIEW

**Comment by deivislaya** [comment]
Hi @JulioSerna 

This Pr is ready for review

**Comment by deivislaya** [comment]
Ready for review

stock card generate odoo

**Comment by JulioSerna** [comment]
@hbto 

What do you think about this PR?
[Video pr dummy](https://youtu.be/eV7MLKnyAF0)

**Comment by hbto** [comment]
@JulioSerna 

> What do you think about this PR?
> [Video pr dummy](https://youtu.be/eV7MLKnyAF0)

+1

**Pull request merged**
