### PR TITLE
[IMP] pr_line_related_po_line: black, isort, prettier T#66087

### PR DESCRIPTION
**Pull request by VEscaname**
Results from running pre-commit-vauxoo on the module

### CODE REVIEW

**Comment by VEscaname** [comment]
Hello, @luisg123v. Do you mind checking these changes?

**Review by luisg123v — CHANGES_REQUESTED** [review]
Missing changes to module's README, there's a missing newline at end of file.

**Comment by luisg123v** [comment]
Missing task ID on title

**Review by luisg123v — APPROVED** [review]
LGTM :+1:

**Pull request merged**
