### PR TITLE
[REF] purchase_order_line_sequence: Added a default method to the definition sequence field in order to avoid the '0' or '1' values when the purchase order lines are massively created.

### LINKED ISSUE #1072: [8.0] purchase_order_line_sequence: Sequence is wrongly generated when purchases orders are created from call for bids
Impacted versions:
[8.0]

Steps to reproduce:

*Go to Call for bids menu, and create new one, add some products and then confirm the call
- Then Request a quotation by clicking the button `Request a Quotation`, Select a partener from the m2o list and continue.

Current behavior:

The Purchase order generated has the purchase order lines with the field sequence wrongly generated, the value is 1 for all of them.

Expected behavior:

The value field sequence must be unique per line in purchase order lines.

Video/Screenshot link (optional):
https://drive.google.com/a/vauxoo.com/file/d/0B_jQX2tloXM7eEdpdDBUSXBGMWM/view?usp=sharing

image

### PR DESCRIPTION
**Pull request by hugho-ad**
fix #1072 (issue)
close Vauxoo/yoytec#2032 (DUMMY)

VIdeo demo
https://drive.google.com/a/vauxoo.com/file/d/0B_jQX2tloXM7Y2xjc012XzNrd2s/view?usp=sharing

image

### CODE REVIEW

**Comment by hugho-ad** [comment]
@zaoral can you review please
this pr solves  this issue https://github.com/Vauxoo/addons-vauxoo/issues/1072

Regards

**Comment by hugho-ad** [comment]
@zaoral 

Can you help me to review this pr that resolves this issue https://github.com/Vauxoo/addons-vauxoo/issues/1072

Regards

**Comment by zaoral** [comment]
Hi @hugho-ad 
Sorry I missed your first comment.
Start reviewing

**Review by zaoral — CHANGES_REQUESTED** [review]
Hi @hugho-ad 
This solution do not fullfil the requirement
Instead, create a new error when trying to create the purchase line from the purchase order.

We need a different solution
I will leave you here the [video](https://youtu.be/R258xjfq6XA) with the functional tests and the explanation

**Comment by hugho-ad** [comment]
@zaoral can you help me please, I added new changes.

Regards

**Comment by hugho-ad** [comment]
@zaoral can you help me to review the new change please

**Review by zaoral — APPROVED** [review]
Functional test +1
Technical review +1

Good job @hugho-ad

**Pull request merged**
