### PR TITLE
[MIG] default_warehouse_from_sale_team: Migrate to v13.0

### PR DESCRIPTION
**Pull request by suniagajose**

### CODE REVIEW

**Comment by suniagajose** [comment]
hi @hugho-ad , @luisg123v 

could you review and merge this?

thanks,

**Review by hugho-ad — CHANGES_REQUESTED** [review]
This module it's not migrated to v13.0

You should migrate it instead of fixing part of the code

**Comment by suniagajose** [comment]
done! @hugho-ad

**Review by luisg123v — CHANGES_REQUESTED** [review]
Hi @suniagajose,

Unfortunately, this branch was created from an old copy of v12. That means the module you're migrating is also outdated, and it doesn't include changes that fix lints and tests (actually the module is red).

Could you cherry pick missing commits, please?

@hugho-ad I will remove all non-migrated modules. I had planned to create the 13.0 branch from scratch to avoid this, but unfortunately Nhomar already started to use that branch.

**Review by luisg123v — CHANGES_REQUESTED** [review]
Hi @suniagajose,

There's only one commit in your PR, which:
- Makes the history to be lost
- Makes harder to review what changes you're actually performing to migrate

To preserve history, run [these commands](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch) (excluding the black/pre-commit part, which we don't use).

For instance:

```
git fetch vauxoo
git format-patch --keep-subject --stdout vauxoo/13.0..vauxoo/12.0 -- default_warehouse_from_sale_team | git am -3 --keep
```

These just before applying your commit to migrate.

**Comment by luisg123v** [comment]
Hi @suniagajose,

As accorded due to conflicts applying the commands I suggested, I performed the migration.

It's in the latest commit.

Could you review, please?

For the record, I'll send an email proposing to re-generate the branch, so such conflicts won't arise on future migrations.

**Comment by suniagajose** [comment]
Thanks @luisg123v 

all seems good for me...

could you merge this, please?

Thanks,

**Comment by suniagajose** [comment]
@luisg123v @hugho-ad 

Technical Review +1

LGTM!

Regards,

**Pull request merged**
