### PR TITLE
[IMP][product_extended_variant]Moved validation that standard_price change before of "for" with all   locations. Because the standard_price not change by location.

### PR DESCRIPTION
**Pull request by luistorresm**
- Moved validation that standard_price change before of "for" with all
  locations. Because the standard_price not change by location.
- Added translation in module
- Fixed pylint

### CODE REVIEW

**Comment by luistorresm** [comment]
@josemoralesp 

Can you give your +1?

Regards

**Comment by josemoralesp** [comment]
@hbto We have some problems with the update cost process in Apex instance.
Basically the process is extremely slow, When @luistorresm was testing the process  took more than 4 days.
With this change @luistorresm  told us that the process takes approximately 7 hour(the expected behavior).
Can you please check these changes and give us your feedback?

Best Regards

**Comment by hbto** [comment]
@josemoralesp please address the slowness of the process with @nhomar 
He has, some time ago, tested a new approach to make process faster

Best Regards

**Comment by josemoralesp** [comment]
@nhomar

**Comment by nhomar** [comment]
Is not this related?

https://github.com/Vauxoo/addons-vauxoo/pull/804/files

I have some comments inline... I like the approach but both of them must come toghether.

Thanks.

**Comment by hbto** [comment]
@nhomar 
No, it is not related,

What @josemoralesp is pointing out is the fact it takes too long to update
the whole universe of products,

some time ago you used another approach where you were creating new 
cronjobs, splitting update of products in sections thus providing a more speedier way.

Do you recall now?

**Comment by nhomar** [comment]
Yes.

https://github.com/Vauxoo/addons-vauxoo/pull/705

You can see the status of the job now.

Note: The splitting process do not have relation with the fact that a process itself is so time consiming.

@luistorresm  Can you chack if your approach has merge problems with mine please?.

Follow tasks pending, what most worry me about is the fact and the leak of unit tests. (pending on my apporach)

Can you merge the jobs and finish the TODO on my PR please?.

**Comment by luisg123v** [comment]
This has conflicts and it's abandoned, so closing.

**Pull request closed without merging**
