### PR TITLE
[REF] CI: Enable vxci to build/push image

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by moylop260** [comment]
@ruiztulio 

Are there something to do extra from a PR based on "-dev" fork?

**Comment by ruiztulio** [comment]
@moylop260 it shouldn't, the only thing that we can need is to add the secrets in vauxoo-dev too, because they aren't shared. It detects the environment checking if the owner ends with -dev

**Comment by moylop260** [comment]
@ruiztulio 

I tried to copy the same values from:
 - https://github.com/Vauxoo/addons-vauxoo/settings/secrets/actions

to:
 - https://github.com/Vauxoo-dev/addons-vauxoo/settings/secrets/actions

But I can not see the values configured

Could you help us to re-configure dev too, please?

**Comment by moylop260** [comment]
@ruiztulio 

Any update here?

**Comment by ruiztulio** [comment]
@moylop260 I missed the message, sorry.

No body can see the values after the have been added:

image

But most of those values are the same from gitlab:

image

Except for the bot credentials, I created a specific bot account for github actions:

image

(you should have access to those credentials in quay.io)

**Edit**: Forgot to mention that I already added the values to https://github.com/Vauxoo-dev/addons-vauxoo/settings/secrets/actions

**Comment by moylop260** [comment]
@ruiztulio 

Do you have any idea why it is failing for PR cases?
 - https://github.com/Vauxoo/addons-vauxoo/actions/runs/3092143347/jobs/5112463253

cc @luisg123v

**Comment by ruiztulio** [comment]
@moylop260 it seems that ssh-agent don't like the key format (don't know why is failing now), but try removing the line:

```bash
ssh-add - <<< "${{ secrets.PRIVATE_DEPLOY_KEY }}"
```

**Comment by luisg123v** [comment]
Superseded by #1590

**Pull request closed without merging**
