### PR TITLE
[MERGE] forwardporting from vauxoo/7.0

### PR DESCRIPTION
**Pull request by moylop260**
Conflicts files:

``` diff
    both modified:   aging_due_report/report/parser.py
    both modified:   project_issue_management/model/project_issue.py
    both modified:   project_issue_management/view/project_issue_view.xml
    both added:      purchase_order_line_quantity/model/purchase_order.py
    both modified:   sprint_kanban/__openerp__.py
    deleted by us:   web_captcha/model/res_captcha.py
```

Please review it

### CODE REVIEW

**Comment by moylop260** [comment]
@hbto and @nhomar,
Can you help me to check this pr?
NOTE: I added description with conflicts files, please review this files very fine!

**Comment by moylop260** [comment]
FYI I will wait builds of next prebuilds:
https://drive.google.com/a/vauxoo.com/file/d/0B4taKTc4rOjsbDZaY0s0U3hfX2s/view?usp=sharing

**Comment by moylop260** [comment]
All runbot builds was without errors.
Except this one:
http://runbot.vauxoo.com/runbot/team/vauxoo-20#64pull_278 - red

**Comment by hbto** [comment]
+1 I agree in changes.

though I was requested to review changes in aging_due_report 
and I can not see any changes in here, could you please
address me to those changes.

Best Regards

**Comment by moylop260** [comment]
@nhomar 
Can you merge it?

**Pull request merged**
