### PR TITLE
Translations and templates sync

### PR DESCRIPTION
**Pull request by sysadminmatmoz**

### CODE REVIEW

**Comment by nhomar** [comment]
@zaoral Please chec this and validate increase version on modules in order to update apps store please.

**Comment by zaoral** [comment]
@nhomar ok. I will start working on it

**Comment by zaoral** [comment]
Hello @sysadminmatmoz,
Thanks for your contribution
I Will check your PR to merge.
I Will let you know soon the results.

Best Regards.

**Comment by zaoral** [comment]
The sync_youtube module update has introduce an error in the translate template. The next are the terms with the error:

```
 #: help:sign.youtube.conf,developer_key:0
 #: help:sign.youtube.conf,client_id:0
```

The original help have a references to a ur link and you propose delete them.
You can see this in the es_VE and es_MX files.
Please fix this.

NOTE: You can check it the commit from you terminal using the git log -p file_path for the next files.
- sync_youtube/i18n/es_MX.po

```
@@ -161,8 +163,7 @@ msgstr "sing.youtube.conf.line"
 #. module: sign_youtube
 #: help:sign.youtube.conf,developer_key:0
 msgid "Developer key used by de API if you do not have one you can get one in the YouTube API https://code.google.com/apis/youtube/dashboard/gwt/index.html#product/
-msgstr "Llave de desarrollador usada por la API. Si usted no posee una usted puede tenerla en este
-enlace  YouTube API https://code.google.com/apis/youtube/dashboard/gwt/index.html#product/AI39si7M7K5jj5AHA-VUGJW0XSgEWIS_qjFkfXwygeIF13AQR85UC2Ylo-8pu2G6gs-Q4MSNKz
+msgstr "Llave de desarrollador usada por la API. Si usted no posee una usted puede tenerla en est"

 #. module: sign_youtube
 #: help:sign.youtube.conf,client_id:0
 msgid "Client ID for your youtube account if you do not have a client ID you can a developer key in the YouTube API https://code.google.com/apis/youtube/dashboard/g
-msgstr "ID de cliente usado por la API YouTube junto a la llave de desarrollador. Si usted no posee
-una puede obtenerla en este link YouTube API https://code.google.com/apis/youtube/dashboard/gwt/index.html#product/AI39si7M7K5jj5AHA-VUGJW0XSgEWIS_qjFkfXwygeIF13AQR
+msgstr "ID de cliente usado por la API YouTube junto a la llave de desarrollador. Si usted no pose"
```
- sync_youtube/i18n/es_VE.po

```
@@ -161,8 +163,7 @@ msgstr "sing.youtube.conf.line"
 #. module: sign_youtube
 #: help:sign.youtube.conf,developer_key:0
 msgid "Developer key used by de API if you do not have one you can get one in the YouTube API https://code.google.com/apis/youtube/dashboard/gwt/index.html#product/
-msgstr "Llave de desarrollador usada por la API. Si usted no posee una usted puede tenerla en este
-enlace  YouTube API https://code.google.com/apis/youtube/dashboard/gwt/index.html#product/AI39si7M7K5jj5AHA-VUGJW0XSgEWIS_qjFkfXwygeIF13AQR85UC2Ylo-8pu2G6gs-Q4MSNKz
+msgstr "Llave de desarrollador usada por la API. Si usted no posee una usted puede tenerla en est"

 #. module: sign_youtube
 #: field:sign.youtube.conf,max_v:0
@@ -172,8 +173,7 @@ msgstr "Numero maximo de videos a cargar"
 #. module: sign_youtube
 #: help:sign.youtube.conf,client_id:0
 msgid "Client ID for your youtube account if you do not have a client ID you can a developer key in the YouTube API https://code.google.com/apis/youtube/dashboard/g
-msgstr "ID de cliente usado por la API YouTube junto a la llave de desarrollador. Si usted no posee
-una puede obtenerla en este link YouTube API https://code.google.com/apis/youtube/dashboard/gwt/index.html#product/AI39si7M7K5jj5AHA-VUGJW0XSgEWIS_qjFkfXwygeIF13AQR
+msgstr "ID de cliente usado por la API YouTube junto a la llave de desarrollador. Si usted no pose"
```

Best Regards

**Comment by nhomar** [comment]
Delete those files please, this module has not been migrated yet to v8

**Comment by sysadminmatmoz** [comment]
The account_chart_wiz_dates and sync_youtube templates were recreated from the source and the related languages updated by them. For the view error on account_bank_statement_vauxoo I'm sorry, but you're on your own. I didn't change any code or views in this PR, only translation templates.

**Pull request merged**
