### PR TITLE
[ADD] Sale Order Gross Margin Percentage

### PR DESCRIPTION
**Pull request by suniagajose**
Summary
-------------

New module to set margin percentage 0 when the purchase price is not set, and show the sale order line in red color. If margin percentage less than 12 % will show the line in yellow.

### CODE REVIEW

**Comment by suniagajose** [comment]
hi @nhomar  @zaoral 

What do you think that is the properly name for this feature?

1- Sale Order margin cost percentage.
2. Sale Order gross margin percentage.
3. Sale Order profit margin percentage.

**Comment by zaoral** [comment]
> 2. Sale Order gross margin percentage.

For me this is the proper option.
@nhomar is up to you what do you think?

**Comment by suniagajose** [comment]
hi @nhomar 

this not work
https://github.com/Vauxoo/addons-vauxoo/pull/1173/files#diff-15ca8cbb46431987342c08ebfceee071R25

can you review this please? 

apparently not recognized the dynamic value 'margin_threshold'... is helpful if you show me a code whit this kind of approach?

thanks,

**Comment by suniagajose** [comment]
@nhomar forget the last comment... It works!!!

so011 odoo

**PD:** not alarm, the column Margin threshold is show only for debug purpose...

**Comment by suniagajose** [comment]
this is ready to merge!

**Pull request merged**
