### PR TITLE
[FIX] aging_due_report: Fixed report "Detailed Aging Report" to future 

### PR DESCRIPTION
**Pull request by luistorresm**
Fixed that when is printed the Detailed Aging Report group correctly the
documents by the corresponding section on date ranges.

Fixed lint errors by order in imports

VX#5955

### CODE REVIEW

**Comment by luistorresm** [comment]
@hbto 

Could you check this PR please?

The report format to future is in this PR description.

Regards

**Comment by hbto** [comment]
@luistorresm could you provide a testing instance for any client using this module

**Comment by luistorresm** [comment]
@hbto 

In this instance is applied this change (http://dev.lodigroup.com:33346)

Regards

**Comment by hbto** [comment]
@luistorresm Thanks a lot I will come back to you with my findings.

Regards

**Comment by hbto** [comment]
+1

Everything looks good to me.

Best Regards

**Comment by luistorresm** [comment]
@moylop260 @nhomar 

Could you merge this PR please?

Regards

**Comment by moylop260** [comment]
FYI I'll delete the message where is used data real here 😞

**Pull request merged**
