### PR TITLE
[FIX] default_warehouse_from_sale_team: decorator on write method

### PR DESCRIPTION
**Pull request by frahikLV**

### CODE REVIEW

**Comment by hugho-ad** [comment]
LGTM :+1:

**Comment by JulioSerna** [comment]
👍

**Comment by hugho-ad** [comment]
@frahikLV 
please check if v12.0 does not need this, in order to forward port it

**Comment by luisg123v** [comment]
@frahikLV,

Did you checked if this needs forward-port?

CC @CarmenMiranda

**Comment by frahikLV** [comment]
@luisg123v  No longer necessary in V12 as the create method is not inherit/called in the "new" version

**Comment by luisg123v** [comment]
@frahikLV,

You're right, in v12 there's only one create method and it already has the appropriate decorator.

Thanks for checking.

**Comment by hugho-ad** [comment]
AFAIK there are not any new version, the create methods was inherited because of the clear caches, a problem that should be persisting on v12.0

**Pull request merged**
