### PR TITLE
[MIG] account_refund_early_payment: Migration to V14.0

### PR DESCRIPTION
**Pull request by luiseevaquer**

### CODE REVIEW

**Comment by luiseevaquer** [comment]
Hi @hugho-ad 

Could you review this MR, please?

**Review by hugho-ad — CHANGES_REQUESTED** [review]
selecting multiple invoices, wizard is not showing the radio buttons as v11.0 
image

image

**Comment by luisg123v** [comment]
This module should be migrated first to 13.0, shouldn't it?

**Comment by hugho-ad** [comment]
@luisg123v  who needs it at v13?

we are prioritizing v14.0 because lasec

**Comment by rsilvam21** [comment]
+1

@hugho-ad for me it is ok

**Review by hugho-ad — CHANGES_REQUESTED** [review]
I test it, but does not reconcile the credit note and the invoice
image


and credit note is reconciled with new journal
image

**Comment by hugho-ad** [comment]
FYI @JulioSerna @hbto 

pls review

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
technically LGTM :+1:

**Comment by hugho-ad** [comment]
@lescobarvx 

pls rebase

ask for funcitonal review pls!

@moylop260 @hbto  could you review pls?

**Comment by moylop260** [comment]
👍

**Comment by hugho-ad** [comment]
@moylop260 @hbto 

could you review pls

**Review by moylop260 — APPROVED** [review]

**Comment by hbto** [comment]
👍

**Pull request merged**
